import type { IdeTask } from "../types";

// Задачи SQL для ЕНТ и школы: базовые запросы на учебной базе (src/lib/ide/sql/db.ts).
// Таблицы: students(id, name, class, city, score), classes(class, teacher, room), books(id, title, author, year, price, pages),
// orders(id, student_id, book_id, qty, ordered). Условия — по числам и латинским словам, чтобы не путать похожие русские/латинские буквы.
// Казахские тексты вычитаны моделью, носителем — нет.
export const TASKS: IdeTask[] = [
  {
    id: "sql-1-select",
    lang: "sql",
    level: 1,
    skill: "db.select",
    title: { ru: "Все данные таблицы", kk: "Кестедегі барлық деректер" },
    prompt: {
      ru: "Выведите **все столбцы и все строки** таблицы `students`.\n\nЗвёздочка `*` в `SELECT` означает «все столбцы».",
      kk: "`students` кестесінің **барлық бағандары мен барлық жолдарын** шығарыңыз.\n\n`SELECT` ішіндегі жұлдызша `*` «барлық бағандар» дегенді білдіреді.",
    },
    starter: "SELECT\nFROM students;",
    hint: {
      ru: "Запрос выглядит так: `SELECT` что выбрать `FROM` откуда. Здесь «что» — все столбцы, а «откуда» — таблица `students`.",
      kk: "Сұраныс былай жазылады: `SELECT` нені таңдау `FROM` қайдан. Мұнда «нені» — барлық бағандар, «қайдан» — `students` кестесі.",
    },
    solution: "SELECT * FROM students;",
    check: { kind: "sql", reference: "SELECT * FROM students" },
  },
  {
    id: "sql-2-columns",
    lang: "sql",
    level: 1,
    skill: "db.select",
    title: { ru: "Выбор столбцов", kk: "Бағандарды таңдау" },
    prompt: {
      ru: "Выведите **имя** и **город** каждого ученика (столбцы `name` и `city`) из таблицы `students`.",
      kk: "`students` кестесінен әр оқушының **атын** және **қаласын** (`name` және `city` бағандары) шығарыңыз.",
    },
    starter: "SELECT\nFROM students;",
    hint: {
      ru: "Названия столбцов перечисляют после `SELECT` через запятую: `SELECT a, b FROM ...`.",
      kk: "Бағандардың атаулары `SELECT` сөзінен кейін үтір арқылы тізіледі: `SELECT a, b FROM ...`.",
    },
    solution: "SELECT name, city FROM students;",
    check: { kind: "sql", reference: "SELECT name, city FROM students" },
  },
  {
    id: "sql-3-order",
    lang: "sql",
    level: 1,
    skill: "db.select",
    title: { ru: "Сортировка по убыванию", kk: "Кему ретімен сұрыптау" },
    prompt: {
      ru: "Выведите **имя** и **балл** (`name`, `score`) всех учеников так, чтобы **сначала шли самые высокие баллы**.",
      kk: "Барлық оқушылардың **атын** және **балын** (`name`, `score`) шығарыңыз: **ең жоғары балдар бірінші** тұрсын.",
    },
    starter: "SELECT name, score\nFROM students\n",
    hint: {
      ru: "Сортировка — `ORDER BY столбец`. По умолчанию она идёт по возрастанию (`ASC`), а по убыванию нужно добавить `DESC`.",
      kk: "Сұрыптау — `ORDER BY баған`. Әдепкіде ол өсу ретімен (`ASC`) жүреді, ал кему ретімен сұрыптау үшін `DESC` қосу керек.",
    },
    solution: "SELECT name, score\nFROM students\nORDER BY score DESC;",
    check: { kind: "sql", reference: "SELECT name, score FROM students ORDER BY score DESC", ordered: true },
  },
  {
    id: "sql-4-where",
    lang: "sql",
    level: 2,
    skill: "db.select",
    title: { ru: "Условие AND и OR", kk: "AND және OR шарты" },
    prompt: {
      ru: "Выведите **имя, класс и балл** (`name`, `class`, `score`) учеников, которые учатся в **10 или 11 классе** и набрали **больше 80 баллов**.",
      kk: "**10-сыныпта немесе 11-сыныпта** оқитын және **80 балдан жоғары** жинаған оқушылардың **атын, сыныбын және балын** (`name`, `class`, `score`) шығарыңыз.",
    },
    starter: "SELECT name, class, score\nFROM students\nWHERE ",
    hint: {
      ru: "Условия соединяют словами `AND` («и») и `OR` («или»). Если смешиваете их, группируйте скобками: `(a OR b) AND c`.",
      kk: "Шарттар `AND` («және») және `OR` («немесе») сөздерімен байланысады. Оларды араластырсаңыз, жақшамен топтаңыз: `(a OR b) AND c`.",
    },
    solution: "SELECT name, class, score\nFROM students\nWHERE (class = 10 OR class = 11) AND score > 80;",
    check: { kind: "sql", reference: "SELECT name, class, score FROM students WHERE (class = 10 OR class = 11) AND score > 80" },
  },
  {
    id: "sql-5-count",
    lang: "sql",
    level: 2,
    skill: "db.select",
    title: { ru: "Подсчёт строк: COUNT", kk: "Жолдарды санау: COUNT" },
    prompt: {
      ru: "Сколько учеников набрали **больше 80 баллов**? Выведите одно число — количество таких учеников.",
      kk: "Қанша оқушы **80 балдан жоғары** жинады? Бір сан шығарыңыз — осындай оқушылардың саны.",
    },
    starter: "SELECT\nFROM students\nWHERE ;",
    hint: {
      ru: "`COUNT(*)` считает строки. Сначала `WHERE` отбирает нужные строки, потом `COUNT(*)` их считает.",
      kk: "`COUNT(*)` жолдарды санайды. Алдымен `WHERE` керекті жолдарды іріктейді, содан кейін `COUNT(*)` оларды санайды.",
    },
    solution: "SELECT COUNT(*)\nFROM students\nWHERE score > 80;",
    check: { kind: "sql", reference: "SELECT COUNT(*) FROM students WHERE score > 80" },
  },
  {
    id: "sql-6-like",
    lang: "sql",
    level: 2,
    skill: "db.select",
    title: { ru: "Поиск по шаблону: LIKE", kk: "Үлгі бойынша іздеу: LIKE" },
    prompt: {
      ru: "В таблице `books` найдите **названия** (`title`) всех книг, в которых есть слово `Python` (в любом месте названия).",
      kk: "`books` кестесінен атауының кез келген жерінде `Python` сөзі бар барлық кітаптардың **атауын** (`title`) табыңыз.",
    },
    starter: "SELECT title\nFROM books\nWHERE title ",
    hint: {
      ru: "В `LIKE` знак `%` заменяет любое количество любых символов: `LIKE '%слово%'` ищет слово в любом месте.",
      kk: "`LIKE` ішіндегі `%` белгісі кез келген таңбалардың кез келген санын алмастырады: `LIKE '%сөз%'` сөзді кез келген жерден іздейді.",
    },
    solution: "SELECT title\nFROM books\nWHERE title LIKE '%Python%';",
    check: { kind: "sql", reference: "SELECT title FROM books WHERE title LIKE '%Python%'" },
  },
  {
    id: "sql-7-group",
    lang: "sql",
    level: 3,
    skill: "db.select",
    title: { ru: "Среднее по группам: AVG и GROUP BY", kk: "Топтар бойынша орташа мән: AVG және GROUP BY" },
    prompt: {
      ru: "Для каждого **класса** найдите **средний балл** учеников. Выведите два столбца: `class` и среднее значение `score`.",
      kk: "Әр **сынып** бойынша оқушылардың **орташа балын** табыңыз. Екі баған шығарыңыз: `class` және `score` бағанының орташа мәні.",
    },
    starter: "SELECT class,\nFROM students\nGROUP BY ",
    hint: {
      ru: "`GROUP BY class` собирает строки в группы по классам, а `AVG(score)` считает среднее отдельно в каждой группе.",
      kk: "`GROUP BY class` жолдарды сыныптар бойынша топтарға жинайды, ал `AVG(score)` орташа мәнді әр топта бөлек есептейді.",
    },
    solution: "SELECT class, AVG(score)\nFROM students\nGROUP BY class;",
    check: { kind: "sql", reference: "SELECT class, AVG(score) FROM students GROUP BY class" },
  },
  {
    id: "sql-8-update",
    lang: "sql",
    level: 3,
    skill: "db.modify",
    title: { ru: "Изменение данных: UPDATE", kk: "Деректерді өзгерту: UPDATE" },
    prompt: {
      ru: "Ученикам **9 класса** добавили по **5 баллов** за олимпиаду. Измените таблицу `students`: увеличьте `score` на 5 только у учеников 9 класса.\n\nПосле запуска ниже покажется таблица `students` — проверьте, что изменились только нужные строки.",
      kk: "**9-сынып** оқушыларына олимпиада үшін **5 балдан** қосылды. `students` кестесін өзгертіңіз: тек 9-сынып оқушыларының `score` мәнін 5-ке арттырыңыз.\n\nІске қосқаннан кейін төменде `students` кестесі көрсетіледі — тек керекті жолдардың өзгергенін тексеріңіз.",
    },
    starter: "UPDATE students\nSET \nWHERE ;",
    hint: {
      ru: "`UPDATE таблица SET столбец = значение WHERE условие`. Новое значение можно считать из старого: `score = score + 5`. Без `WHERE` изменятся все строки!",
      kk: "`UPDATE кесте SET баған = мән WHERE шарт`. Жаңа мәнді ескісінен есептеуге болады: `score = score + 5`. `WHERE` болмаса, барлық жолдар өзгереді!",
    },
    solution: "UPDATE students\nSET score = score + 5\nWHERE class = 9;",
    check: { kind: "sql", reference: "UPDATE students SET score = score + 5 WHERE class = 9", checkQuery: "SELECT * FROM students ORDER BY id" },
  },

  // ───────── Курс 2.0: навыки db.where / db.order / db.group / db.join / db.ddl ─────────
  {
    id: "sql-9-between",
    lang: "sql",
    level: 1,
    skill: "db.where",
    title: { ru: "Диапазон: BETWEEN", kk: "Аралық: BETWEEN" },
    prompt: {
      ru: "В таблице `books` найдите книги, цена которых **от 3000 до 4500** (границы входят в диапазон). Выведите `title` и `price`.",
      kk: "`books` кестесінен бағасы **3000 мен 4500 аралығында** (екі шекті де қоса алғанда) болатын кітаптарды табыңыз. `title` және `price` бағандарын шығарыңыз.",
    },
    starter: "SELECT title, price\nFROM books\nWHERE price ",
    hint: {
      ru: "`BETWEEN a AND b` значит «между a и b» и **включает обе границы**: `x BETWEEN a AND b` — то же, что `x >= a AND x <= b`.",
      kk: "`BETWEEN a AND b` «a мен b аралығында» дегенді білдіреді және **екі шекті де қамтиды**: `x BETWEEN a AND b` жазуы `x >= a AND x <= b` жазуымен бірдей.",
    },
    solution: "SELECT title, price\nFROM books\nWHERE price BETWEEN 3000 AND 4500;",
    check: { kind: "sql", reference: "SELECT title, price FROM books WHERE price BETWEEN 3000 AND 4500" },
  },
  {
    id: "sql-10-in",
    lang: "sql",
    level: 2,
    skill: "db.where",
    title: { ru: "Список значений: IN", kk: "Мәндер тізімі: IN" },
    prompt: {
      ru: "В таблице `books` найдите книги авторов `Brown`, `Taylor` или `Wilson`, изданные **в 2020 году или позже**. Выведите `title`, `author` и `year`.",
      kk: "`books` кестесінен авторлары `Brown`, `Taylor` немесе `Wilson` болатын және **2020 жылы немесе одан кейін** шыққан кітаптарды табыңыз. `title`, `author` және `year` бағандарын шығарыңыз.",
    },
    starter: "SELECT title, author, year\nFROM books\nWHERE author \n  AND year ",
    hint: {
      ru: "`author IN ('a', 'b', 'c')` заменяет длинную цепочку `OR`. Текст пишут в одинарных кавычках. Второе условие присоедините через `AND`.",
      kk: "`author IN ('a', 'b', 'c')` ұзын `OR` тізбегін алмастырады. Мәтін жалғыз тырнақшада жазылады. Екінші шартты `AND` арқылы қосыңыз.",
    },
    solution: "SELECT title, author, year\nFROM books\nWHERE author IN ('Brown', 'Taylor', 'Wilson')\n  AND year >= 2020;",
    check: { kind: "sql", reference: "SELECT title, author, year FROM books WHERE author IN ('Brown', 'Taylor', 'Wilson') AND year >= 2020" },
  },
  {
    id: "sql-11-like-or",
    lang: "sql",
    level: 3,
    skill: "db.where",
    title: { ru: "LIKE с «_» и скобки", kk: "«_» бар LIKE және жақшалар" },
    prompt: {
      ru: "Даты в `orders` хранятся текстом, например `'2026-09-15'`. Среди заказов, сделанных **с 10 по 19 сентября**, найдите те, в которых **больше одного экземпляра** (`qty > 1`) **или** книга с `book_id = 4`. Выведите `id`, `ordered`, `qty` и `book_id`.",
      kk: "`orders` кестесінде күндер мәтін түрінде сақталады, мысалы `'2026-09-15'`. **10–19 қыркүйек** аралығында жасалған тапсырыстардың ішінен саны **бір данадан көп** (`qty > 1`) **немесе** кітабы `book_id = 4` болатындарын табыңыз. `id`, `ordered`, `qty` және `book_id` бағандарын шығарыңыз.",
    },
    starter: "SELECT id, ordered, qty, book_id\nFROM orders\nWHERE ordered LIKE \n  AND ",
    hint: {
      ru: "В `LIKE` знак `_` заменяет **ровно один** символ: `'2026-08-2_'` подходит к датам с 20 по 29 августа. Условия с `OR` возьмите в скобки, иначе `AND` свяжется не с тем.",
      kk: "`LIKE` ішіндегі `_` белгісі **дәл бір** таңбаны алмастырады: `'2026-08-2_'` 20–29 тамыз аралығындағы күндерге сәйкес келеді. `OR` бар шарттарды жақшаға алыңыз, әйтпесе `AND` басқа шартпен байланысады.",
    },
    solution: "SELECT id, ordered, qty, book_id\nFROM orders\nWHERE ordered LIKE '2026-09-1_'\n  AND (qty > 1 OR book_id = 4);",
    check: {
      kind: "sql",
      reference: "SELECT id, ordered, qty, book_id FROM orders WHERE ordered LIKE '2026-09-1_' AND (qty > 1 OR book_id = 4)",
    },
  },
  {
    id: "sql-12-distinct",
    lang: "sql",
    level: 1,
    skill: "db.order",
    title: { ru: "Без повторов: DISTINCT", kk: "Қайталаусыз: DISTINCT" },
    prompt: {
      ru: "Выведите **годы издания** книг (`year`) из таблицы `books` **без повторов** и **по возрастанию**. Один столбец — `year`.",
      kk: "`books` кестесіндегі кітаптардың **шыққан жылдарын** (`year`) **қайталамай** және **өсу ретімен** шығарыңыз. Бір баған — `year`.",
    },
    starter: "SELECT year\nFROM books\n",
    hint: {
      ru: "`SELECT DISTINCT столбец` убирает повторяющиеся значения. Сортировка по возрастанию — `ORDER BY` без `DESC`.",
      kk: "`SELECT DISTINCT баған` қайталанатын мәндерді алып тастайды. Өсу ретімен сұрыптау — `DESC` сөзі жоқ `ORDER BY`.",
    },
    solution: "SELECT DISTINCT year\nFROM books\nORDER BY year;",
    check: { kind: "sql", reference: "SELECT DISTINCT year FROM books ORDER BY year", ordered: true },
  },
  {
    id: "sql-13-order-limit",
    lang: "sql",
    level: 2,
    skill: "db.order",
    title: { ru: "Два ключа сортировки и LIMIT", kk: "Екі сұрыптау кілті және LIMIT" },
    prompt: {
      ru: "Выведите `name`, `class` и `score` учеников, отсортировав **сначала по классу (по возрастанию)**, а **внутри класса — по баллу (по убыванию)**. Покажите только **первые 5 строк**.",
      kk: "Оқушылардың `name`, `class` және `score` бағандарын шығарыңыз: **алдымен сынып бойынша (өсу ретімен)**, ал **сынып ішінде бал бойынша (кему ретімен)** сұрыптаңыз. Тек **алғашқы 5 жолды** көрсетіңіз.",
    },
    starter: "SELECT name, class, score\nFROM students\nORDER BY \n",
    hint: {
      ru: "Ключи сортировки перечисляют через запятую: `ORDER BY a, b DESC`. Слово `DESC` относится только к тому столбцу, после которого стоит. `LIMIT n` в самом конце оставляет первые n строк.",
      kk: "Сұрыптау кілттері үтір арқылы тізіледі: `ORDER BY a, b DESC`. `DESC` сөзі тек өзінің алдындағы бағанға қатысты. Соңындағы `LIMIT n` алғашқы n жолды қалдырады.",
    },
    solution: "SELECT name, class, score\nFROM students\nORDER BY class, score DESC\nLIMIT 5;",
    check: { kind: "sql", reference: "SELECT name, class, score FROM students ORDER BY class, score DESC LIMIT 5", ordered: true },
  },
  {
    id: "sql-14-aggregates",
    lang: "sql",
    level: 1,
    skill: "db.group",
    title: { ru: "COUNT, MIN и MAX", kk: "COUNT, MIN және MAX" },
    prompt: {
      ru: "В таблице `books` найдите **количество книг**, **самую низкую** и **самую высокую** цену. Выведите три значения в одной строке.",
      kk: "`books` кестесінен **кітаптар санын**, **ең төмен** және **ең жоғары** бағаны табыңыз. Үш мәнді бір жолда шығарыңыз.",
    },
    starter: "SELECT\nFROM books;",
    hint: {
      ru: "Функции можно перечислить через запятую в одном `SELECT`: `COUNT(*)`, `MIN(столбец)`, `MAX(столбец)`. Без `GROUP BY` результат — одна строка.",
      kk: "Функцияларды бір `SELECT` ішінде үтір арқылы тізуге болады: `COUNT(*)`, `MIN(баған)`, `MAX(баған)`. `GROUP BY` болмаса, нәтиже — бір жол.",
    },
    solution: "SELECT COUNT(*), MIN(price), MAX(price)\nFROM books;",
    check: { kind: "sql", reference: "SELECT COUNT(*), MIN(price), MAX(price) FROM books" },
  },
  {
    id: "sql-15-group-city",
    lang: "sql",
    level: 2,
    skill: "db.group",
    title: { ru: "GROUP BY: итоги по городам", kk: "GROUP BY: қалалар бойынша қорытынды" },
    prompt: {
      ru: "Для каждого **города** найдите **число учеников** и **наивысший балл**. Выведите `city`, число учеников и максимальный `score`.",
      kk: "Әр **қала** бойынша **оқушылар санын** және **ең жоғары балды** табыңыз. `city`, оқушылар санын және `score` бағанының ең үлкен мәнін шығарыңыз.",
    },
    starter: "SELECT city,\nFROM students\nGROUP BY ",
    hint: {
      ru: "`GROUP BY city` собирает строки в группы по городам. В `SELECT` кроме `city` ставят только агрегатные функции — они считаются отдельно по каждой группе. Подумайте, какая функция считает строки, а какая находит наибольшее значение.",
      kk: "`GROUP BY city` жолдарды қалалар бойынша топтарға жинайды. `SELECT` ішінде `city` бағанынан басқа тек агрегаттық функциялар тұрады — олар әр топ үшін бөлек есептеледі. Қай функция жолдарды санайтынын, ал қайсысы ең үлкен мәнді табатынын ойлаңыз.",
    },
    solution: "SELECT city, COUNT(*), MAX(score)\nFROM students\nGROUP BY city;",
    check: { kind: "sql", reference: "SELECT city, COUNT(*), MAX(score) FROM students GROUP BY city" },
  },
  {
    id: "sql-16-having",
    lang: "sql",
    level: 3,
    skill: "db.group",
    title: { ru: "WHERE и HAVING вместе", kk: "WHERE және HAVING бірге" },
    prompt: {
      ru: "В таблице `orders` среди заказов, сделанных **не раньше `2026-09-08`**, найдите учеников, заказавших **в сумме не меньше 2 экземпляров** книг. Выведите `student_id` и сумму `qty`.",
      kk: "`orders` кестесінде **`2026-09-08` күні немесе одан кейін** жасалған тапсырыстардың ішінен **жалпы саны кемінде 2 дана** кітапқа тапсырыс берген оқушыларды табыңыз. `student_id` және `qty` қосындысын шығарыңыз.",
    },
    starter: "SELECT student_id, SUM(qty)\nFROM orders\nWHERE \nGROUP BY \nHAVING ",
    hint: {
      ru: "`WHERE` отбирает строки **до** группировки (здесь — по дате), а `HAVING` проверяет условие **для групп** (здесь — по `SUM(qty)`). Порядок: `WHERE`, `GROUP BY`, `HAVING`. Даты вида `'ГГГГ-ММ-ДД'` сравнивают как обычный текст: `ordered < '2026-01-01'`.",
      kk: "`WHERE` жолдарды топтауға **дейін** іріктейді (мұнда — күн бойынша), ал `HAVING` шартты **топтар үшін** тексереді (мұнда — `SUM(qty)` бойынша). Реті: `WHERE`, `GROUP BY`, `HAVING`. `'ЖЖЖЖ-АА-КК'` түріндегі күндер кәдімгі мәтін сияқты салыстырылады: `ordered < '2026-01-01'`.",
    },
    solution: "SELECT student_id, SUM(qty)\nFROM orders\nWHERE ordered >= '2026-09-08'\nGROUP BY student_id\nHAVING SUM(qty) >= 2;",
    check: {
      kind: "sql",
      reference: "SELECT student_id, SUM(qty) FROM orders WHERE ordered >= '2026-09-08' GROUP BY student_id HAVING SUM(qty) >= 2",
    },
  },
  {
    id: "sql-17-join-room",
    lang: "sql",
    level: 2,
    skill: "db.join",
    title: { ru: "JOIN: ученики и кабинеты", kk: "JOIN: оқушылар және кабинеттер" },
    prompt: {
      ru: "Выведите **имя** каждого ученика, набравшего **больше 85 баллов**, и **кабинет** (`room`) его класса. Таблицы `students` и `classes` связаны по столбцу `class`.",
      kk: "**85 балдан жоғары** жинаған әр оқушының **атын** және оның сыныбының **кабинетін** (`room`) шығарыңыз. `students` және `classes` кестелері `class` бағаны арқылы байланысқан.",
    },
    starter: "SELECT students.name, classes.room\nFROM students\nJOIN \nWHERE ",
    hint: {
      ru: "`FROM a JOIN b ON a.class = b.class` соединяет строки с одинаковым значением связи. Столбец `class` есть в обеих таблицах — пишите `таблица.столбец`.",
      kk: "`FROM a JOIN b ON a.class = b.class` байланыс мәні бірдей жолдарды қосады. `class` бағаны екі кестеде де бар — `кесте.баған` түрінде жазыңыз.",
    },
    solution: "SELECT students.name, classes.room\nFROM students\nJOIN classes ON students.class = classes.class\nWHERE students.score > 85;",
    check: {
      kind: "sql",
      reference: "SELECT students.name, classes.room FROM students JOIN classes ON students.class = classes.class WHERE students.score > 85",
    },
  },
  {
    id: "sql-18-join-total",
    lang: "sql",
    level: 3,
    skill: "db.join",
    title: { ru: "JOIN: стоимость заказа", kk: "JOIN: тапсырыс құны" },
    prompt: {
      ru: "Для заказов из `orders` выведите **название книги** (`title`) и **стоимость заказа** (цена × количество), но только для заказов **дороже 8000**.",
      kk: "`orders` кестесіндегі тапсырыстар бойынша **кітап атауын** (`title`) және **тапсырыс құнын** (баға × саны) шығарыңыз, тек құны **8000-нан жоғары** тапсырыстарды көрсетіңіз.",
    },
    starter: "SELECT books.title,\nFROM orders\nJOIN \nWHERE ",
    hint: {
      ru: "В `orders` номер книги хранится в `book_id`, а в `books` — в `id`: по ним и соединяйте. Стоимость — арифметическое выражение из столбцов двух таблиц; его можно писать и в `SELECT`, и в `WHERE`.",
      kk: "`orders` кестесінде кітаптың нөмірі `book_id` бағанында, ал `books` кестесінде `id` бағанында сақталады: кестелерді солар арқылы қосыңыз. Құны — екі кестенің бағандарынан құралған арифметикалық өрнек; оны `SELECT` ішінде де, `WHERE` ішінде де жазуға болады.",
    },
    solution: "SELECT books.title, books.price * orders.qty\nFROM orders\nJOIN books ON orders.book_id = books.id\nWHERE books.price * orders.qty > 8000;",
    check: {
      kind: "sql",
      reference:
        "SELECT books.title, books.price * orders.qty FROM orders JOIN books ON orders.book_id = books.id WHERE books.price * orders.qty > 8000",
    },
  },
  {
    id: "sql-19-insert",
    lang: "sql",
    level: 1,
    skill: "db.ddl",
    title: { ru: "Добавление строки: INSERT", kk: "Жол қосу: INSERT" },
    prompt: {
      ru: "В таблицу `classes` добавьте новый класс: **7**, учитель `Ivanov K.`, кабинет **108**. Столбцы идут в порядке `class`, `teacher`, `room`.\n\nПосле запуска ниже покажется таблица `classes` — проверьте, что появилась новая строка.",
      kk: "`classes` кестесіне жаңа сынып қосыңыз: **7**, мұғалім `Ivanov K.`, кабинет **108**. Бағандар `class`, `teacher`, `room` ретімен орналасқан.\n\nІске қосқаннан кейін төменде `classes` кестесі көрсетіледі — жаңа жолдың пайда болғанын тексеріңіз.",
    },
    starter: "INSERT INTO classes\nVALUES ();",
    hint: {
      ru: "`INSERT INTO таблица VALUES (значение1, значение2, ...)`. Значения идут в порядке столбцов таблицы, текст — в одинарных кавычках.",
      kk: "`INSERT INTO кесте VALUES (мән1, мән2, ...)`. Мәндер кесте бағандарының ретімен жазылады, мәтін — жалғыз тырнақшада.",
    },
    solution: "INSERT INTO classes\nVALUES (7, 'Ivanov K.', 108);",
    check: { kind: "sql", reference: "INSERT INTO classes VALUES (7, 'Ivanov K.', 108)", checkQuery: "SELECT * FROM classes ORDER BY class" },
  },
  {
    id: "sql-20-delete",
    lang: "sql",
    level: 3,
    skill: "db.ddl",
    title: { ru: "Удаление строк: DELETE", kk: "Жолдарды жою: DELETE" },
    prompt: {
      ru: "Библиотека списывает старые книги. Из таблицы `books` удалите книги, изданные **раньше 2020 года**, если они **стоят не больше 3000** или в них **больше 350 страниц** (`pages`).\n\nПосле запуска ниже покажется таблица `books` — проверьте, что остались только нужные строки.",
      kk: "Кітапхана ескі кітаптарды есептен шығарады. `books` кестесінен **2020 жылға дейін** шыққан кітаптардың ішінен **бағасы 3000-нан аспайтын** немесе **беті 350-ден көп** (`pages`) кітаптарды жойыңыз.\n\nІске қосқаннан кейін төменде `books` кестесі көрсетіледі — тек керекті жолдардың қалғанын тексеріңіз.",
    },
    starter: "DELETE FROM books\nWHERE ;",
    hint: {
      ru: "`DELETE FROM таблица WHERE условие`. `AND` выполняется раньше `OR` — подумайте, какие условия нужно сгруппировать скобками. «Не больше» — это `<=`. Без `WHERE` удалятся **все** строки!",
      kk: "`DELETE FROM кесте WHERE шарт`. `AND` амалы `OR` амалынан бұрын орындалады — қай шарттарды жақшамен топтау керектігін ойлаңыз. «Аспайтын» — бұл `<=`. `WHERE` болмаса, **барлық** жолдар жойылады!",
    },
    solution: "DELETE FROM books\nWHERE year < 2020 AND (price <= 3000 OR pages > 350);",
    check: {
      kind: "sql",
      reference: "DELETE FROM books WHERE year < 2020 AND (price <= 3000 OR pages > 350)",
      checkQuery: "SELECT * FROM books ORDER BY id",
    },
  },
];
