import type { IdeTask } from "../types";
import type { PyForbid } from "./check";

// Задачи «Практикума» — Python (ЕНТ: ввод-вывод, ветвления, циклы, строки, списки, функции, алгоритмы).
// Стиль как в ЕНТ: короткое условие, ввод — строки stdin, вывод — через print. Слова в выводе — латиницей (even/odd, yes/no),
// чтобы не зависеть от языка интерфейса. Тесты эталонов — tests/ide-python.test.ts (системный python3).
export const TASKS: IdeTask[] = [
  {
    id: "py-1-hello",
    lang: "python",
    level: 1,
    skill: "py.vars",
    title: { ru: "Вывод и арифметика", kk: "Шығару және арифметика" },
    prompt: {
      ru: "Выведите сумму, разность и произведение чисел 12 и 5 — каждое на отдельной строке.\n\nОжидаемый вывод:\n\n```\n17\n7\n60\n```",
      kk: "12 және 5 сандарының қосындысын, айырмасын және көбейтіндісін шығарыңыз — әрқайсысы жеке жолға.\n\nКүтілетін шығыс:\n\n```\n17\n7\n60\n```",
    },
    starter: "print(12 + 5)\n",
    hint: {
      ru: "`print(12 + 5)` выводит сумму. Добавьте ещё две строки с `print` — для вычитания `-` и умножения `*`.",
      kk: "`print(12 + 5)` қосындыны шығарады. Азайту `-` және көбейту `*` үшін тағы екі `print` жолын қосыңыз.",
    },
    solution: "print(12 + 5)\nprint(12 - 5)\nprint(12 * 5)\n",
    check: { kind: "python", tests: [{ stdout: "17\n7\n60" }] },
  },
  {
    id: "py-2-sum",
    lang: "python",
    level: 1,
    skill: "py.vars",
    title: { ru: "Сумма двух чисел", kk: "Екі санның қосындысы" },
    prompt: {
      ru: "Программа получает два целых числа — каждое на своей строке. Выведите их сумму.\n\nПример: ввод `3` и `5` → вывод `8`.",
      kk: "Программа екі бүтін сан алады — әрқайсысы жеке жолда. Олардың қосындысын шығарыңыз.\n\nМысал: енгізу `3` және `5` → шығыс `8`.",
    },
    starter: "a = int(input())\nb = int(input())\n",
    hint: {
      ru: "`input()` читает строку, а `int(...)` превращает её в число.",
      kk: "`input()` жолды оқиды, ал `int(...)` оны санға айналдырады.",
    },
    solution: "a = int(input())\nb = int(input())\nprint(a + b)\n",
    check: {
      kind: "python",
      tests: [
        { stdin: "3\n5\n", stdout: "8" },
        { stdin: "-4\n10\n", stdout: "6" },
        { stdin: "100\n250\n", stdout: "350" },
      ],
    },
  },
  {
    id: "py-3-parity",
    lang: "python",
    level: 1,
    skill: "py.if",
    title: { ru: "Чётное или нечётное", kk: "Жұп па, тақ па" },
    prompt: {
      ru: "Дано целое число. Выведите слово `even`, если оно чётное, и `odd` — если нечётное.",
      kk: "Бүтін сан берілген. Сан жұп болса, `even`, тақ болса, `odd` сөзін шығарыңыз.",
    },
    starter: "n = int(input())\n",
    hint: {
      ru: "Число чётное, если остаток от деления на 2 равен нулю: `n % 2 == 0`. Используйте `if` и `else`.",
      kk: "Санды 2-ге бөлгендегі қалдық нөлге тең болса, ол жұп болады: `n % 2 == 0`. `if` және `else` қолданыңыз.",
    },
    solution: 'n = int(input())\nif n % 2 == 0:\n    print("even")\nelse:\n    print("odd")\n',
    check: {
      kind: "python",
      tests: [
        { stdin: "7\n", stdout: "odd" },
        { stdin: "10\n", stdout: "even" },
        { stdin: "0\n", stdout: "even" },
        { stdin: "-3\n", stdout: "odd" },
      ],
    },
  },
  {
    id: "py-4-max3",
    lang: "python",
    level: 2,
    skill: "py.if",
    title: { ru: "Наибольшее из трёх", kk: "Үшеуінің ең үлкені" },
    prompt: {
      ru: "Даны три целых числа (каждое на своей строке). Выведите наибольшее из них. Решите с помощью `if`, без функции `max`.",
      kk: "Үш бүтін сан берілген (әрқайсысы жеке жолда). Олардың ең үлкенін шығарыңыз. `if` арқылы шешіңіз, `max` функциясын қолданбаңыз.",
    },
    starter: "a = int(input())\nb = int(input())\nc = int(input())\n",
    hint: {
      ru: "Сначала решите, что наибольшее — `a`. Если `b` больше, замените на `b`; затем так же сравните с `c`.",
      kk: "Алдымен ең үлкені — `a` деп алыңыз. `b` одан үлкен болса, ең үлкені — `b`; содан кейін `c` санымен де солай салыстырыңыз.",
    },
    solution: "a = int(input())\nb = int(input())\nc = int(input())\nbest = a\nif b > best:\n    best = b\nif c > best:\n    best = c\nprint(best)\n",
    check: {
      kind: "python",
      tests: [
        { stdin: "3\n9\n5\n", stdout: "9" },
        { stdin: "10\n2\n7\n", stdout: "10" },
        { stdin: "-1\n-5\n-3\n", stdout: "-1" },
        { stdin: "4\n4\n4\n", stdout: "4" },
        { stdin: "1\n2\n3\n", stdout: "3" },
        { stdin: "7\n7\n2\n", stdout: "7" },
        { stdin: "5\n1\n5\n", stdout: "5" },
      ],
    },
  },
  {
    id: "py-5-sum-for",
    lang: "python",
    level: 2,
    skill: "py.loops",
    title: { ru: "Сумма от 1 до n (цикл for)", kk: "1-ден n санына дейінгі қосынды (for циклі)" },
    prompt: {
      ru: "Дано натуральное число `n`. Выведите сумму 1 + 2 + … + n. Используйте цикл `for`.\n\nПример: `n = 5` → `15`.",
      kk: "`n` натурал саны берілген. 1 + 2 + … + n қосындысын шығарыңыз. `for` циклін қолданыңыз.\n\nМысал: `n = 5` → `15`.",
    },
    starter: "n = int(input())\ntotal = 0\n",
    hint: {
      ru: "`for i in range(1, n + 1):` перебирает числа от 1 до n. На каждом шаге прибавляйте `i` к `total`.",
      kk: "`for i in range(1, n + 1):` 1-ден бастап n санына дейінгі сандарды аралайды. Әр қадамда `i` санын `total` айнымалысына қосыңыз.",
    },
    solution: "n = int(input())\ntotal = 0\nfor i in range(1, n + 1):\n    total += i\nprint(total)\n",
    check: {
      kind: "python",
      tests: [
        { stdin: "1\n", stdout: "1" },
        { stdin: "5\n", stdout: "15" },
        { stdin: "10\n", stdout: "55" },
        { stdin: "100\n", stdout: "5050" },
      ],
    },
  },
  {
    id: "py-6-digit-sum",
    lang: "python",
    level: 2,
    skill: "py.loops",
    title: { ru: "Сумма цифр числа (цикл while)", kk: "Сан цифрларының қосындысы (while циклі)" },
    prompt: {
      ru: "Дано натуральное число. Выведите сумму его цифр. Используйте цикл `while`.\n\nПример: `123` → `6`.",
      kk: "Натурал сан берілген. Оның цифрларының қосындысын шығарыңыз. `while` циклін қолданыңыз.\n\nМысал: `123` → `6`.",
    },
    starter: "n = int(input())\ntotal = 0\n",
    hint: {
      ru: "Последняя цифра — `n % 10`, а число без последней цифры — `n // 10`. Повторяйте, пока `n > 0`.",
      kk: "Соңғы цифр — `n % 10`, ал соңғы цифрсыз сан — `n // 10`. `n > 0` болғанша қайталаңыз.",
    },
    solution: "n = int(input())\ntotal = 0\nwhile n > 0:\n    total += n % 10\n    n //= 10\nprint(total)\n",
    check: {
      kind: "python",
      tests: [
        { stdin: "123\n", stdout: "6" },
        { stdin: "7\n", stdout: "7" },
        { stdin: "9999\n", stdout: "36" },
        { stdin: "1000\n", stdout: "1" },
        { stdin: "2026\n", stdout: "10" },
      ],
    },
  },
  {
    id: "py-7-vowels",
    lang: "python",
    level: 2,
    skill: "py.strings",
    title: { ru: "Гласные в строке", kk: "Жолдағы дауысты әріптер" },
    prompt: {
      ru: "Дана строка из латинских букв и пробелов. Выведите, сколько в ней гласных `a`, `e`, `i`, `o`, `u` (заглавные тоже считаются).\n\nПример: `informatics` → `4`.",
      kk: "Латын әріптері мен бос орындардан тұратын жол берілген. Ондағы `a`, `e`, `i`, `o`, `u` дауысты әріптерінің санын шығарыңыз (бас әріптер де есептеледі).\n\nМысал: `informatics` → `4`.",
    },
    starter: "s = input()\ncount = 0\n",
    hint: {
      ru: 'Переберите символы циклом `for ch in s:` и проверяйте условие `ch.lower() in "aeiou"`.',
      kk: '`for ch in s:` циклімен жолдың таңбаларын аралап, `ch.lower() in "aeiou"` шартын тексеріңіз.',
    },
    solution: 's = input()\ncount = 0\nfor ch in s:\n    if ch.lower() in "aeiou":\n        count += 1\nprint(count)\n',
    check: {
      kind: "python",
      tests: [
        { stdin: "informatics\n", stdout: "4" },
        { stdin: "Hello World\n", stdout: "3" },
        { stdin: "rhythm\n", stdout: "0" },
        { stdin: "AEIOU\n", stdout: "5" },
        { stdin: "Python programming\n", stdout: "4" },
      ],
    },
  },
  {
    id: "py-8-list-stats",
    lang: "python",
    level: 2,
    skill: "py.lists",
    title: { ru: "Среднее и наибольшее в списке", kk: "Тізімдегі орташа мән және ең үлкен сан" },
    prompt: {
      ru: "В первой строке — количество чисел `n`, во второй — сами числа через пробел. Выведите среднее арифметическое (результат обычного деления `/`) и наибольшее число — каждое на своей строке.\n\nПример: `5` и `3 9 4 8 6` → `6.0` и `9`.",
      kk: "Бірінші жолда — сандар саны `n`, екінші жолда — сандардың өздері бос орын арқылы. Орташа арифметикалық мәнді (кәдімгі `/` бөлудің нәтижесін) және ең үлкен санды шығарыңыз — әрқайсысы жеке жолға.\n\nМысал: `5` және `3 9 4 8 6` → `6.0` және `9`.",
    },
    starter: "n = int(input())\na = list(map(int, input().split()))\n",
    hint: {
      ru: "Пригодятся `sum(a)`, `len(a)` и `max(a)`. Среднее — это сумма, делённая на количество.",
      kk: "`sum(a)`, `len(a)` және `max(a)` керек болады. Орташа мән — қосындыны сандар санына бөлгендегі нәтиже.",
    },
    solution: "n = int(input())\na = list(map(int, input().split()))\nprint(sum(a) / len(a))\nprint(max(a))\n",
    check: {
      kind: "python",
      tests: [
        { stdin: "5\n3 9 4 8 6\n", stdout: "6.0\n9" },
        { stdin: "4\n1 2 3 4\n", stdout: "2.5\n4" },
        { stdin: "3\n-5 -1 -3\n", stdout: "-3.0\n-1" },
        { stdin: "1\n42\n", stdout: "42.0\n42" },
      ],
    },
  },
  {
    id: "py-9-function",
    lang: "python",
    level: 3,
    skill: "py.functions",
    title: { ru: "Функция: простое число", kk: "Функция: жай сан" },
    prompt: {
      ru: "Напишите функцию `is_prime(n)`: она возвращает `True`, если число `n` простое, и `False`, если нет (число 1 не простое). Программа читает число и выводит `yes` или `no`.\n\nПример: `17` → `yes`, `18` → `no`.",
      kk: "Егер `n` саны жай болса `True`, әйтпесе `False` қайтаратын `is_prime(n)` функциясын жазыңыз (1 саны жай емес). Программа санды оқиды да, `yes` немесе `no` шығарады.\n\nМысал: `17` → `yes`, `18` → `no`.",
    },
    starter: 'def is_prime(n):\n    return False\n\n\nn = int(input())\nif is_prime(n):\n    print("yes")\nelse:\n    print("no")\n',
    hint: {
      ru: "Число простое, если у него нет делителей, начиная с 2 и пока `d * d <= n`. Проверяйте `n % d == 0`. Не забудьте про `n < 2`.",
      kk: "Сан жай болу үшін оның 2-ден бастап `d * d <= n` болғанша бөлгіштері болмауы керек. `n % d == 0` шартын тексеріңіз. `n < 2` жағдайын ұмытпаңыз.",
    },
    solution:
      'def is_prime(n):\n    if n < 2:\n        return False\n    d = 2\n    while d * d <= n:\n        if n % d == 0:\n            return False\n        d += 1\n    return True\n\n\nn = int(input())\nif is_prime(n):\n    print("yes")\nelse:\n    print("no")\n',
    check: {
      kind: "python",
      tests: [
        { stdin: "2\n", stdout: "yes" },
        { stdin: "1\n", stdout: "no" },
        { stdin: "17\n", stdout: "yes" },
        { stdin: "18\n", stdout: "no" },
        { stdin: "91\n", stdout: "no" },
        { stdin: "97\n", stdout: "yes" },
        { stdin: "9\n", stdout: "no" },
        { stdin: "49\n", stdout: "no" },
        { stdin: "4\n", stdout: "no" },
      ],
    },
  },
  {
    id: "py-10-binary",
    lang: "python",
    level: 3,
    skill: "py.algos",
    title: { ru: "Перевод в двоичную систему", kk: "Екілік жүйеге аудару" },
    prompt: {
      ru: "Дано натуральное число `n`. Выведите его запись в двоичной системе счисления. Функции `bin` и `format` не используйте — переводите вручную: делите на 2 и собирайте остатки.\n\nПример: `10` → `1010`.",
      kk: "`n` натурал саны берілген. Оның екілік санау жүйесіндегі жазбасын шығарыңыз. `bin` және `format` функцияларын қолданбаңыз — қолмен аударыңыз: 2-ге бөліп, қалдықтарды жинаңыз.\n\nМысал: `10` → `1010`.",
    },
    starter: 'n = int(input())\ns = ""\n',
    hint: {
      ru: "Пока `n > 0`: припишите слева к строке `s` остаток `n % 2` (как строку, `str(...)`), затем замените `n` на `n // 2`.",
      kk: "`n > 0` болғанша: `s` жолының сол жағына `n % 2` қалдығын (жол ретінде, `str(...)`) жалғаңыз, содан кейін `n` мәнін `n // 2` мәніне ауыстырыңыз.",
    },
    solution: 'n = int(input())\ns = ""\nwhile n > 0:\n    s = str(n % 2) + s\n    n //= 2\nprint(s)\n',
    check: {
      kind: "python",
      tests: [
        { stdin: "10\n", stdout: "1010" },
        { stdin: "1\n", stdout: "1" },
        { stdin: "37\n", stdout: "100101" },
        { stdin: "64\n", stdout: "1000000" },
        { stdin: "255\n", stdout: "11111111" },
      ],
    },
  },
  {
    id: "py-11-io-sep",
    lang: "python",
    level: 1,
    skill: "py.io",
    title: { ru: "Вывод через разделитель", kk: "Бөлгішпен шығару" },
    prompt: {
      ru: "Даны три слова — каждое на своей строке. Выведите их в одной строке через дефис, без пробелов.\n\nПример: `red`, `green`, `blue` → `red-green-blue`.",
      kk: "Үш сөз берілген — әрқайсысы жеке жолда. Оларды бір жолға, бос орынсыз, дефис арқылы шығарыңыз.\n\nМысал: `red`, `green`, `blue` → `red-green-blue`.",
    },
    starter: "a = input()\nb = input()\nc = input()\nprint(a, b, c)\n",
    hint: {
      ru: "У `print` есть параметр `sep` — разделитель между значениями: `print(a, b, sep=\"+\")`.",
      kk: "`print` функциясында `sep` параметрі бар — ол мәндер арасындағы бөлгіш: `print(a, b, sep=\"+\")`.",
    },
    solution: "a = input()\nb = input()\nc = input()\nprint(a, b, c, sep=\"-\")\n",
    check: {
      kind: "python",
      tests: [
        { stdin: "red\ngreen\nblue\n", stdout: "red-green-blue" },
        { stdin: "x\ny\nz\n", stdout: "x-y-z" },
        { stdin: "Kazakhstan\nAstana\n2026\n", stdout: "Kazakhstan-Astana-2026" },
        { stdin: "a\nb\nc\n", stdout: "a-b-c" },
      ],
    },
  },
  {
    id: "py-12-types-concat",
    lang: "python",
    level: 1,
    skill: "py.types",
    title: { ru: "Строки и числа", kk: "Жолдар және сандар" },
    prompt: {
      ru: "Даны два целых неотрицательных числа — каждое на своей строке. На первой строке выведите результат их **склейки** как строк, на второй — их сумму как чисел.\n\nПример: `12` и `34` → `1234` и `46`.",
      kk: "Екі теріс емес бүтін сан берілген — әрқайсысы жеке жолда. Бірінші жолға оларды жол ретінде **жалғау** нәтижесін, екінші жолға сан ретінде қосындысын шығарыңыз.\n\nМысал: `12` және `34` → `1234` және `46`.",
    },
    starter: "a = input()\nb = input()\n",
    hint: {
      ru: "`input()` возвращает строку, а `+` для строк — склейка. Для суммы чисел сначала превратите строки в числа: `int(a)`.",
      kk: "`input()` жол қайтарады, ал жолдар үшін `+` — жалғау. Сандардың қосындысы үшін алдымен жолдарды санға айналдырыңыз: `int(a)`.",
    },
    solution: "a = input()\nb = input()\nprint(a + b)\nprint(int(a) + int(b))\n",
    check: {
      kind: "python",
      tests: [
        { stdin: "12\n34\n", stdout: "1234\n46" },
        { stdin: "5\n7\n", stdout: "57\n12" },
        { stdin: "100\n1\n", stdout: "1001\n101" },
        { stdin: "0\n9\n", stdout: "09\n9" },
      ],
    },
  },
  {
    id: "py-13-ops-time",
    lang: "python",
    level: 1,
    skill: "py.ops",
    title: { ru: "Секунды в часы и минуты", kk: "Секундтарды сағат пен минутқа айналдыру" },
    prompt: {
      ru: "Дано число секунд `t` (0 ≤ t < 86400). Выведите через пробел, сколько в нём полных часов, минут и секунд.\n\nПример: `3725` → `1 2 5`.",
      kk: "`t` секунд саны берілген (0 ≤ t < 86400). Онда неше толық сағат, минут және секунд бар екенін бос орын арқылы шығарыңыз.\n\nМысал: `3725` → `1 2 5`.",
    },
    starter: "t = int(input())\n",
    hint: {
      ru: "Часы — `t // 3600`. Остаток секунд — `t % 3600`; из него минуты — `// 60`, а секунды — `% 60`.",
      kk: "Сағат — `t // 3600`. Қалған секунд — `t % 3600`; одан минут — `// 60`, ал секунд — `% 60`.",
    },
    solution: "t = int(input())\nh = t // 3600\nm = t % 3600 // 60\ns = t % 60\nprint(h, m, s)\n",
    check: {
      kind: "python",
      tests: [
        { stdin: "3725\n", stdout: "1 2 5" },
        { stdin: "59\n", stdout: "0 0 59" },
        { stdin: "3600\n", stdout: "1 0 0" },
        { stdin: "86399\n", stdout: "23 59 59" },
        { stdin: "0\n", stdout: "0 0 0" },
        { stdin: "61\n", stdout: "0 1 1" },
      ],
    },
  },
  {
    id: "py-14-ops-digit",
    lang: "python",
    level: 2,
    skill: "py.ops",
    title: { ru: "Цифра в разряде", kk: "Разрядтағы цифр" },
    prompt: {
      ru: "Даны натуральное число `n` и номер разряда `k` — каждое на своей строке. Выведите цифру числа `n`, стоящую в `k`-м разряде справа (единицы — разряд 1). Если в числе меньше `k` цифр, выведите `0`. Используйте только арифметику (`//`, `%`, `**`) — без строк и индексов.\n\nПример: `5274` и `3` → `2`.",
      kk: "`n` натурал саны және `k` разряд нөмірі берілген — әрқайсысы жеке жолда. `n` санының оң жақтан санағанда `k` нөмірлі разрядында тұрған цифрын шығарыңыз (бірліктер — 1-разряд). Санда `k` цифрдан аз болса, `0` шығарыңыз. Тек арифметиканы (`//`, `%`, `**`) қолданыңыз — жолдарсыз және индекстерсіз.\n\nМысал: `5274` және `3` → `2`.",
    },
    starter: "n = int(input())\nk = int(input())\n",
    hint: {
      ru: "`10 ** (k - 1)` — это единица в `k`-м разряде. Целочисленное деление на неё отбрасывает младшие разряды, и нужная цифра становится последней — а последнюю цифру даёт `% 10`.",
      kk: "`10 ** (k - 1)` — `k` нөмірлі разрядтың бірлігі. Осы санға бүтін бөлу кіші разрядтарды алып тастайды, сонда керекті цифр соңғы болып қалады — ал соңғы цифрды `% 10` береді.",
    },
    solution: "n = int(input())\nk = int(input())\nprint(n // 10 ** (k - 1) % 10)\n",
    check: {
      kind: "python",
      tests: [
        { stdin: "5274\n3\n", stdout: "2" },
        { stdin: "5274\n1\n", stdout: "4" },
        { stdin: "5274\n4\n", stdout: "5" },
        { stdin: "5274\n6\n", stdout: "0" },
        { stdin: "7\n1\n", stdout: "7" },
        { stdin: "90817\n2\n", stdout: "1" },
        { stdin: "90817\n4\n", stdout: "0" },
        { stdin: "1000000\n7\n", stdout: "1" },
      ],
    },
  },
  {
    id: "py-15-cond-ticket",
    lang: "python",
    level: 1,
    skill: "py.cond",
    title: { ru: "Билет в кино", kk: "Киноға билет" },
    prompt: {
      ru: "Возраст зрителя — целое число `a`. Выведите `child`, если a < 12; `teen`, если 12 ≤ a ≤ 17; иначе выведите `adult`.",
      kk: "Көрермен жасы — `a` бүтін саны. a < 12 болса `child`, 12 ≤ a ≤ 17 болса `teen`, әйтпесе `adult` шығарыңыз.",
    },
    starter: "a = int(input())\n",
    hint: {
      ru: "Проверяйте по порядку: `if a < 12:`, затем `elif a <= 17:`, иначе `else:`. Ветка `elif` выполняется, только если первое условие ложно.",
      kk: "Шарттарды ретімен тексеріңіз: `if a < 12:`, содан соң `elif a <= 17:`, әйтпесе `else:`. `elif` тармағы бірінші шарт жалған болғанда ғана орындалады.",
    },
    solution: "a = int(input())\nif a < 12:\n    print(\"child\")\nelif a <= 17:\n    print(\"teen\")\nelse:\n    print(\"adult\")\n",
    check: {
      kind: "python",
      tests: [
        { stdin: "5\n", stdout: "child" },
        { stdin: "11\n", stdout: "child" },
        { stdin: "12\n", stdout: "teen" },
        { stdin: "17\n", stdout: "teen" },
        { stdin: "18\n", stdout: "adult" },
        { stdin: "40\n", stdout: "adult" },
        { stdin: "0\n", stdout: "child" },
      ],
    },
  },
  {
    id: "py-16-cond-triangle",
    lang: "python",
    level: 2,
    skill: "py.cond",
    title: { ru: "Вид треугольника", kk: "Үшбұрыш түрі" },
    prompt: {
      ru: "Даны три натуральных числа — длины отрезков (каждое на своей строке). Если треугольника с такими сторонами не существует, выведите `no`. Иначе выведите `equilateral` (все стороны равны), `isosceles` (равны ровно две) или `scalene` (все разные).\n\nТреугольник существует, если каждая сторона меньше суммы двух других.",
      kk: "Үш натурал сан берілген — кесінділердің ұзындықтары (әрқайсысы жеке жолда). Мұндай қабырғалы үшбұрыш болмаса, `no` шығарыңыз. Әйтпесе `equilateral` (барлық қабырғасы тең), `isosceles` (дәл екеуі тең) немесе `scalene` (барлығы әртүрлі) шығарыңыз.\n\nӘр қабырға қалған екеуінің қосындысынан кіші болса, үшбұрыш бар болады.",
    },
    starter: "a = int(input())\nb = int(input())\nc = int(input())\n",
    hint: {
      ru: "Сначала проверьте, что треугольник существует: `a < b + c and b < a + c and c < a + b`. Затем сравните стороны: `a == b == c`, и `a == b or b == c or a == c`.",
      kk: "Алдымен үшбұрыштың бар-жоғын тексеріңіз: `a < b + c and b < a + c and c < a + b`. Содан кейін қабырғаларды салыстырыңыз: `a == b == c` және `a == b or b == c or a == c`.",
    },
    solution: "a = int(input())\nb = int(input())\nc = int(input())\nif not (a < b + c and b < a + c and c < a + b):\n    print(\"no\")\nelif a == b == c:\n    print(\"equilateral\")\nelif a == b or b == c or a == c:\n    print(\"isosceles\")\nelse:\n    print(\"scalene\")\n",
    check: {
      kind: "python",
      tests: [
        { stdin: "3\n3\n3\n", stdout: "equilateral" },
        { stdin: "3\n3\n5\n", stdout: "isosceles" },
        { stdin: "3\n4\n5\n", stdout: "scalene" },
        { stdin: "1\n2\n3\n", stdout: "no" },
        { stdin: "1\n1\n5\n", stdout: "no" },
        { stdin: "5\n3\n3\n", stdout: "isosceles" },
        { stdin: "3\n5\n3\n", stdout: "isosceles" },
        { stdin: "2\n7\n2\n", stdout: "no" },
      ],
    },
  },
  {
    id: "py-17-for-down",
    lang: "python",
    level: 1,
    skill: "py.for",
    title: { ru: "Обратный отсчёт", kk: "Кері санақ" },
    prompt: {
      ru: "Дано натуральное число `n`. Выведите числа от `n` до 1 в одной строке через пробел.\n\nПример: `5` → `5 4 3 2 1`.",
      kk: "`n` натурал саны берілген. `n` санынан бастап 1-ге дейінгі сандарды бір жолға бос орын арқылы кему ретімен шығарыңыз.\n\nМысал: `5` → `5 4 3 2 1`.",
    },
    starter: "n = int(input())\n",
    hint: {
      ru: "`range(n, 0, -1)` перебирает числа от `n` вниз до 1 (третий параметр — шаг). Чтобы не переводить строку, пишите `print(i, end=\" \")`.",
      kk: "`range(n, 0, -1)` сандарды `n` санынан 1-ге дейін кему ретімен аралайды (үшінші параметр — қадам). Жаңа жолға өтпеу үшін `print(i, end=\" \")` жазыңыз.",
    },
    solution: "n = int(input())\nfor i in range(n, 0, -1):\n    print(i, end=\" \")\nprint()\n",
    check: {
      kind: "python",
      tests: [
        { stdin: "5\n", stdout: "5 4 3 2 1" },
        { stdin: "1\n", stdout: "1" },
        { stdin: "10\n", stdout: "10 9 8 7 6 5 4 3 2 1" },
        { stdin: "3\n", stdout: "3 2 1" },
      ],
    },
  },
  {
    id: "py-18-while-halves",
    lang: "python",
    level: 1,
    skill: "py.while",
    title: { ru: "Сколько раз разделить пополам", kk: "Неше рет екіге бөлу керек" },
    prompt: {
      ru: "Дано натуральное число `n`. Сколько раз его нужно разделить нацело на 2 (`n // 2`), чтобы получить 0? Выведите это количество. Используйте `while`.\n\nПример: `8` → `4` (8 → 4 → 2 → 1 → 0).",
      kk: "`n` натурал саны берілген. Нөл алу үшін оны неше рет 2-ге бүтін бөлу (`n // 2`) керек? Осы санды шығарыңыз. `while` қолданыңыз.\n\nМысал: `8` → `4` (8 → 4 → 2 → 1 → 0).",
    },
    starter: "n = int(input())\nk = 0\n",
    hint: {
      ru: "Заведите счётчик `k = 0`. Пока `n > 0`: заменяйте `n` на `n // 2` и увеличивайте `k` на 1.",
      kk: "`k = 0` санауышын алыңыз. `n > 0` болғанша: `n` мәнін `n // 2` мәніне ауыстырып, `k` мәнін 1-ге арттырыңыз.",
    },
    solution: "n = int(input())\nk = 0\nwhile n > 0:\n    n //= 2\n    k += 1\nprint(k)\n",
    check: {
      kind: "python",
      tests: [
        { stdin: "8\n", stdout: "4" },
        { stdin: "1\n", stdout: "1" },
        { stdin: "1000\n", stdout: "10" },
        { stdin: "7\n", stdout: "3" },
        { stdin: "1024\n", stdout: "11" },
        { stdin: "2\n", stdout: "2" },
      ],
    },
  },
  {
    id: "py-19-while-stop",
    lang: "python",
    level: 2,
    skill: "py.while",
    title: { ru: "Сумма до нуля", kk: "Нөлге дейінгі қосынды" },
    prompt: {
      ru: "Числа вводятся по одному на строке; когда введён `0`, чтение заканчивается. Выведите сумму положительных чисел; отрицательные пропускайте (`continue`).\n\nПример: `5`, `-3`, `7`, `0` → `12`.",
      kk: "Сандар әр жолға бір-бірден беріледі; `0` енгізілгенде оқу тоқтайды. Оң сандардың қосындысын шығарыңыз; теріс сандарды өткізіп жіберіңіз (`continue`).\n\nМысал: `5`, `-3`, `7`, `0` → `12`.",
    },
    starter: "total = 0\n",
    hint: {
      ru: "Цикл `while True:` читает число. Если оно `0` — `break`; если отрицательное — `continue`; иначе прибавьте его к сумме.",
      kk: "`while True:` циклі санды оқиды. Ол `0` болса — `break`; теріс болса — `continue`; әйтпесе оны қосындыға қосыңыз.",
    },
    solution: "total = 0\nwhile True:\n    x = int(input())\n    if x == 0:\n        break\n    if x < 0:\n        continue\n    total += x\nprint(total)\n",
    check: {
      kind: "python",
      tests: [
        { stdin: "5\n-3\n7\n0\n", stdout: "12" },
        { stdin: "0\n", stdout: "0" },
        { stdin: "-1\n-2\n0\n", stdout: "0" },
        { stdin: "3\n0\n9\n", stdout: "3" },
        { stdin: "10\n20\n30\n0\n", stdout: "60" },
      ],
    },
  },
  {
    id: "py-20-nested-table",
    lang: "python",
    level: 2,
    skill: "py.nested",
    title: { ru: "Таблица умножения", kk: "Көбейту кестесі" },
    prompt: {
      ru: "Дано натуральное число `n`. Выведите таблицу умножения размера n × n: в строке с номером `i` — произведения `i · 1`, `i · 2`, …, `i · n` через пробел.\n\nПример: `3` →\n\n```\n1 2 3\n2 4 6\n3 6 9\n```",
      kk: "`n` натурал саны берілген. n × n өлшемді көбейту кестесін шығарыңыз: `i` нөмірлі жолда `i · 1`, `i · 2`, …, `i · n` көбейтінділері бос орын арқылы жазылады.\n\nМысал: `3` →\n\n```\n1 2 3\n2 4 6\n3 6 9\n```",
    },
    starter: "n = int(input())\n",
    hint: {
      ru: "Внешний цикл `for i in range(1, n + 1)` — строки, внутренний `for j in range(1, n + 1)` — числа в строке: `print(i * j, end=\" \")`. После внутреннего цикла нужен пустой `print()` — переход на новую строку.",
      kk: "Сыртқы `for i in range(1, n + 1)` циклі — жолдар, ішкі `for j in range(1, n + 1)` циклі — жолдағы сандар: `print(i * j, end=\" \")`. Ішкі циклден кейін жаңа жолға өту үшін бос `print()` қажет.",
    },
    solution: "n = int(input())\nfor i in range(1, n + 1):\n    for j in range(1, n + 1):\n        print(i * j, end=\" \")\n    print()\n",
    check: {
      kind: "python",
      tests: [
        { stdin: "3\n", stdout: "1 2 3\n2 4 6\n3 6 9" },
        { stdin: "1\n", stdout: "1" },
        { stdin: "4\n", stdout: "1 2 3 4\n2 4 6 8\n3 6 9 12\n4 8 12 16" },
        { stdin: "5\n", stdout: "1 2 3 4 5\n2 4 6 8 10\n3 6 9 12 15\n4 8 12 16 20\n5 10 15 20 25" },
      ],
    },
  },
  {
    id: "py-21-pat-maxpos",
    lang: "python",
    level: 2,
    skill: "py.patterns",
    title: { ru: "Наибольшее и его номер", kk: "Ең үлкен сан және оның нөмірі" },
    prompt: {
      ru: "В первой строке — количество чисел `n`, во второй — сами числа через пробел. Выведите наибольшее число и номер (считая с 1) его первого вхождения — каждое на своей строке. Функцию `max` и метод `index` не используйте.\n\nПример: `5` и `3 9 4 9 6` → `9` и `2`.",
      kk: "Бірінші жолда — сандар саны `n`, екінші жолда — сандардың өздері бос орын арқылы. Ең үлкен санды және оның бірінші кездескен орнының нөмірін (1-ден бастап санағанда) шығарыңыз — әрқайсысы жеке жолға. `max` функциясын және `index` әдісін қолданбаңыз.\n\nМысал: `5` және `3 9 4 9 6` → `9` және `2`.",
    },
    starter: "n = int(input())\na = list(map(int, input().split()))\n",
    hint: {
      ru: "Запомните `best = a[0]` и `pos = 1`. Перебирайте `for i in range(1, n)`: если `a[i] > best` (строго больше!), обновите `best` и `pos = i + 1`.",
      kk: "`best = a[0]` және `pos = 1` деп алыңыз. `for i in range(1, n)` бойынша аралаңыз: `a[i] > best` (қатаң үлкен!) болса, `best` мәнін және `pos = i + 1` мәнін жаңартыңыз.",
    },
    solution: "n = int(input())\na = list(map(int, input().split()))\nbest = a[0]\npos = 1\nfor i in range(1, n):\n    if a[i] > best:\n        best = a[i]\n        pos = i + 1\nprint(best)\nprint(pos)\n",
    check: {
      kind: "python",
      tests: [
        { stdin: "5\n3 9 4 9 6\n", stdout: "9\n2" },
        { stdin: "1\n7\n", stdout: "7\n1" },
        { stdin: "4\n-5 -2 -9 -2\n", stdout: "-2\n2" },
        { stdin: "3\n1 2 3\n", stdout: "3\n3" },
        { stdin: "3\n3 2 1\n", stdout: "3\n1" },
        { stdin: "6\n4 4 4 4 4 4\n", stdout: "4\n1" },
      ],
    },
  },
  {
    id: "py-22-pat-reverse",
    lang: "python",
    level: 2,
    skill: "py.patterns",
    title: { ru: "Число наоборот", kk: "Сан кері ретпен" },
    prompt: {
      ru: "Дано натуральное число. Выведите число, записанное теми же цифрами в обратном порядке (нули в начале не пишутся). Работайте с цифрами арифметикой — без строк, индексов и срезов.\n\nПример: `1230` → `321`.",
      kk: "Натурал сан берілген. Сол цифрлармен кері ретпен жазылған санды шығарыңыз (алдыңғы нөлдер жазылмайды). Цифрларды арифметикамен өңдеңіз — жолдарсыз, индекстерсіз және тілімдерсіз.\n\nМысал: `1230` → `321`.",
    },
    starter: "n = int(input())\nrev = 0\n",
    hint: {
      ru: "Пока `n > 0`: `rev = rev * 10 + n % 10` (приписываем последнюю цифру справа), затем `n //= 10`.",
      kk: "`n > 0` болғанша: `rev = rev * 10 + n % 10` (соңғы цифрды оң жағына жазамыз), содан кейін `n //= 10`.",
    },
    solution: "n = int(input())\nrev = 0\nwhile n > 0:\n    rev = rev * 10 + n % 10\n    n //= 10\nprint(rev)\n",
    check: {
      kind: "python",
      tests: [
        { stdin: "123\n", stdout: "321" },
        { stdin: "1230\n", stdout: "321" },
        { stdin: "7\n", stdout: "7" },
        { stdin: "100\n", stdout: "1" },
        { stdin: "4025\n", stdout: "5204" },
        { stdin: "98765\n", stdout: "56789" },
      ],
    },
  },
  {
    id: "py-23-pat-gcd",
    lang: "python",
    level: 3,
    skill: "py.patterns",
    title: { ru: "НОД: алгоритм Евклида", kk: "ЕҮОБ: Евклид алгоритмі" },
    prompt: {
      ru: "Даны два натуральных числа (каждое на своей строке). Выведите их наибольший общий делитель (НОД). Модуль `math` (и его `gcd`) не используйте — примените алгоритм Евклида.\n\nПример: `12` и `18` → `6`.",
      kk: "Екі натурал сан берілген (әрқайсысы жеке жолда). Олардың ең үлкен ортақ бөлгішін (ЕҮОБ) шығарыңыз. `math` модулін (және оның `gcd` функциясын) қолданбаңыз — Евклид алгоритмін пайдаланыңыз.\n\nМысал: `12` және `18` → `6`.",
    },
    starter: "a = int(input())\nb = int(input())\n",
    hint: {
      ru: "Алгоритм Евклида: пока `b != 0`, заменяйте пару `(a, b)` на `(b, a % b)`. Ответ — `a`.",
      kk: "Евклид алгоритмі: `b != 0` болғанша `(a, b)` жұбын `(b, a % b)` жұбына ауыстырыңыз. Жауап — `a`.",
    },
    solution: "a = int(input())\nb = int(input())\nwhile b != 0:\n    a, b = b, a % b\nprint(a)\n",
    check: {
      kind: "python",
      tests: [
        { stdin: "12\n18\n", stdout: "6" },
        { stdin: "17\n5\n", stdout: "1" },
        { stdin: "100\n75\n", stdout: "25" },
        { stdin: "7\n7\n", stdout: "7" },
        { stdin: "48\n180\n", stdout: "12" },
        { stdin: "5\n1000\n", stdout: "5" },
      ],
    },
  },
  {
    id: "py-24-str-palindrome",
    lang: "python",
    level: 2,
    skill: "py.strmethods",
    title: { ru: "Палиндром", kk: "Палиндром" },
    prompt: {
      ru: "Дано слово из строчных латинских букв. Выведите `yes`, если оно читается одинаково слева направо и справа налево, иначе — `no`.\n\nПример: `level` → `yes`, `python` → `no`.",
      kk: "Кіші латын әріптерінен тұратын сөз берілген. Ол солдан оңға және оңнан солға бірдей оқылса `yes`, әйтпесе `no` шығарыңыз.\n\nМысал: `level` → `yes`, `python` → `no`.",
    },
    starter: "s = input()\n",
    hint: {
      ru: "Срез `s[::-1]` — это строка наоборот. Сравните её с самой строкой `s`.",
      kk: "`s[::-1]` тілімі — жолдың кері жазылуы. Оны `s` жолының өзімен салыстырыңыз.",
    },
    solution: "s = input()\nif s == s[::-1]:\n    print(\"yes\")\nelse:\n    print(\"no\")\n",
    check: {
      kind: "python",
      tests: [
        { stdin: "level\n", stdout: "yes" },
        { stdin: "python\n", stdout: "no" },
        { stdin: "a\n", stdout: "yes" },
        { stdin: "abba\n", stdout: "yes" },
        { stdin: "abc\n", stdout: "no" },
        { stdin: "noon\n", stdout: "yes" },
        { stdin: "ab\n", stdout: "no" },
      ],
    },
  },
  {
    id: "py-25-list-evens",
    lang: "python",
    level: 2,
    skill: "py.listops",
    title: { ru: "Чётные числа списка", kk: "Тізімдегі жұп сандар" },
    prompt: {
      ru: "В первой строке — количество чисел `n`, во второй — сами числа через пробел. Выведите чётные числа в исходном порядке через пробел. Если чётных чисел нет, выведите `none`.\n\nПример: `5` и `3 8 5 10 7` → `8 10`.",
      kk: "Бірінші жолда — сандар саны `n`, екінші жолда — сандардың өздері бос орын арқылы. Жұп сандарды бастапқы реті бойынша бос орын арқылы шығарыңыз. Жұп сан болмаса, `none` шығарыңыз.\n\nМысал: `5` және `3 8 5 10 7` → `8 10`.",
    },
    starter: "n = int(input())\na = list(map(int, input().split()))\nres = []\n",
    hint: {
      ru: "Заведите пустой список `res = []` и добавляйте подходящие числа через `res.append(x)`. Вывести список через пробел можно так: `print(*res)`. Не забудьте случай пустого списка.",
      kk: "Бос `res = []` тізімін алып, шартқа сай сандарды `res.append(x)` арқылы қосыңыз. Тізімді бос орын арқылы былай шығаруға болады: `print(*res)`. Бос тізім жағдайын ұмытпаңыз.",
    },
    solution: "n = int(input())\na = list(map(int, input().split()))\nres = []\nfor x in a:\n    if x % 2 == 0:\n        res.append(x)\nif len(res) == 0:\n    print(\"none\")\nelse:\n    print(*res)\n",
    check: {
      kind: "python",
      tests: [
        { stdin: "5\n3 8 5 10 7\n", stdout: "8 10" },
        { stdin: "3\n1 3 5\n", stdout: "none" },
        { stdin: "4\n2 4 6 8\n", stdout: "2 4 6 8" },
        { stdin: "1\n0\n", stdout: "0" },
        { stdin: "4\n-2 -3 -4 1\n", stdout: "-2 -4" },
      ],
    },
  },
  {
    id: "py-26-list-rotate",
    lang: "python",
    level: 2,
    skill: "py.listops",
    title: { ru: "Последний — в начало", kk: "Соңғысы — басына" },
    prompt: {
      ru: "В первой строке — количество чисел `n`, во второй — сами числа через пробел. Переместите последнее число в начало списка и выведите список через пробел.\n\nПример: `4` и `1 2 3 4` → `4 1 2 3`.",
      kk: "Бірінші жолда — сандар саны `n`, екінші жолда — сандардың өздері бос орын арқылы. Соңғы санды тізімнің басына жылжытып, тізімді бос орын арқылы шығарыңыз.\n\nМысал: `4` және `1 2 3 4` → `4 1 2 3`.",
    },
    starter: "n = int(input())\na = list(map(int, input().split()))\n",
    hint: {
      ru: "`a.pop()` удаляет последний элемент и возвращает его, а `a.insert(0, x)` вставляет `x` в начало списка.",
      kk: "`a.pop()` соңғы элементті жояды да, оны қайтарады, ал `a.insert(0, x)` `x` мәнін тізімнің басына қояды.",
    },
    solution: "n = int(input())\na = list(map(int, input().split()))\nx = a.pop()\na.insert(0, x)\nprint(*a)\n",
    check: {
      kind: "python",
      tests: [
        { stdin: "4\n1 2 3 4\n", stdout: "4 1 2 3" },
        { stdin: "1\n5\n", stdout: "5" },
        { stdin: "2\n7 -1\n", stdout: "-1 7" },
        { stdin: "5\n9 8 7 6 5\n", stdout: "5 9 8 7 6" },
      ],
    },
  },
  {
    id: "py-27-matrix-diag",
    lang: "python",
    level: 3,
    skill: "py.matrix",
    title: { ru: "Диагонали таблицы", kk: "Кесте диагональдары" },
    prompt: {
      ru: "В первой строке — размер `n` квадратной таблицы, затем `n` строк по `n` чисел через пробел. Выведите сумму элементов главной диагонали (`a[i][i]`) и сумму элементов побочной диагонали (`a[i][n-1-i]`) — каждую на своей строке.\n\nПример: `3`, строки `1 2 3`, `4 5 6`, `7 8 10` → `16` и `15`.",
      kk: "Бірінші жолда — шаршы кестенің `n` өлшемі, одан кейін `n` жол, әр жолда `n` сан бос орын арқылы. Бас диагональ элементтерінің қосындысын (`a[i][i]`) және қосалқы диагональ элементтерінің қосындысын (`a[i][n-1-i]`) шығарыңыз — әрқайсысы жеке жолға.\n\nМысал: `3`, жолдар `1 2 3`, `4 5 6`, `7 8 10` → `16` және `15`.",
    },
    starter: "n = int(input())\na = []\nfor i in range(n):\n    a.append(list(map(int, input().split())))\n",
    hint: {
      ru: "Заготовка уже читает таблицу. Достаточно одного цикла по `i`: прибавляйте `a[i][i]` к первой сумме и `a[i][n - 1 - i]` — ко второй.",
      kk: "Бастапқы код кестені оқып қойған. `i` бойынша бір цикл жеткілікті: `a[i][i]` мәнін бірінші қосындыға, `a[i][n - 1 - i]` мәнін екінші қосындыға қосыңыз.",
    },
    solution: "n = int(input())\na = []\nfor i in range(n):\n    a.append(list(map(int, input().split())))\nmain = 0\nside = 0\nfor i in range(n):\n    main += a[i][i]\n    side += a[i][n - 1 - i]\nprint(main)\nprint(side)\n",
    check: {
      kind: "python",
      tests: [
        { stdin: "3\n1 2 3\n4 5 6\n7 8 10\n", stdout: "16\n15" },
        { stdin: "1\n5\n", stdout: "5\n5" },
        { stdin: "2\n1 2\n3 4\n", stdout: "5\n5" },
        { stdin: "4\n1 0 0 2\n0 3 4 0\n0 5 6 0\n7 0 0 8\n", stdout: "18\n18" },
        { stdin: "3\n-1 2 -3\n4 -5 6\n-7 8 -9\n", stdout: "-15\n-15" },
      ],
    },
  },
  {
    id: "py-28-params-minmax",
    lang: "python",
    level: 2,
    skill: "py.params",
    title: { ru: "Функция minmax", kk: "minmax функциясы" },
    prompt: {
      ru: "Напишите функцию `minmax(a)`, которая возвращает два значения: наименьший и наибольший элементы списка `a`. Программа читает числа через пробел и выводит результат функции через пробел.\n\nПример: `4 9 -2 7` → `-2 9`.",
      kk: "`minmax(a)` функциясын жазыңыз: ол екі мән қайтарады — `a` тізімінің ең кіші және ең үлкен элементтерін. Программа сандарды бос орын арқылы оқиды да, функция нәтижесін бос орын арқылы шығарады.\n\nМысал: `4 9 -2 7` → `-2 9`.",
    },
    starter: "def minmax(a):\n    pass\n\n\na = list(map(int, input().split()))\nlo, hi = minmax(a)\nprint(lo, hi)\n",
    hint: {
      ru: "Функция может вернуть сразу два значения: `return x, y`. Принять их можно так: `lo, hi = minmax(a)`.",
      kk: "Функция бірден екі мән қайтара алады: `return x, y`. Оларды былай қабылдауға болады: `lo, hi = minmax(a)`.",
    },
    solution: "def minmax(a):\n    return min(a), max(a)\n\n\na = list(map(int, input().split()))\nlo, hi = minmax(a)\nprint(lo, hi)\n",
    check: {
      kind: "python",
      tests: [
        { stdin: "4 9 -2 7\n", stdout: "-2 9" },
        { stdin: "5\n", stdout: "5 5" },
        { stdin: "-3 -8 -1\n", stdout: "-8 -1" },
        { stdin: "1 2 3 4 5\n", stdout: "1 5" },
        { stdin: "10 10 10\n", stdout: "10 10" },
      ],
    },
  },
  {
    id: "py-29-rec-fib",
    lang: "python",
    level: 3,
    skill: "py.recursion",
    title: { ru: "Фибоначчи: рекурсия", kk: "Фибоначчи: рекурсия" },
    prompt: {
      ru: "Числа Фибоначчи: F(1) = 1, F(2) = 1, F(n) = F(n − 1) + F(n − 2). Напишите рекурсивную функцию `fib(n)` и выведите F(n) для введённого `n` (n ≤ 20). Циклы не используйте.\n\nПример: `7` → `13`.",
      kk: "Фибоначчи сандары: F(1) = 1, F(2) = 1, F(n) = F(n − 1) + F(n − 2). Рекурсивті `fib(n)` функциясын жазып, енгізілген `n` үшін F(n) мәнін шығарыңыз (n ≤ 20). Циклдерді қолданбаңыз.\n\nМысал: `7` → `13`.",
    },
    starter: "def fib(n):\n    return 0\n\n\nn = int(input())\nprint(fib(n))\n",
    hint: {
      ru: "Сначала база рекурсии: для каких `n` ответ известен сразу? Для остальных `n` функция вызывает саму себя — дважды, по формуле из условия.",
      kk: "Алдымен рекурсия базасы: қандай `n` үшін жауап бірден белгілі? Қалған `n` үшін функция өзін-өзі шақырады — шарттағы формула бойынша екі рет.",
    },
    solution: "def fib(n):\n    if n <= 2:\n        return 1\n    return fib(n - 1) + fib(n - 2)\n\n\nn = int(input())\nprint(fib(n))\n",
    check: {
      kind: "python",
      tests: [
        { stdin: "1\n", stdout: "1" },
        { stdin: "2\n", stdout: "1" },
        { stdin: "7\n", stdout: "13" },
        { stdin: "10\n", stdout: "55" },
        { stdin: "20\n", stdout: "6765" },
        { stdin: "15\n", stdout: "610" },
      ],
    },
  },
  {
    id: "py-30-sort-bubble",
    lang: "python",
    level: 3,
    skill: "py.sort",
    title: { ru: "Пузырёк: число обменов", kk: "Көпіршік: алмасулар саны" },
    prompt: {
      ru: "В первой строке — количество чисел `n`, во второй — сами числа через пробел. Отсортируйте список по возрастанию методом пузырька (соседние элементы сравниваются и при необходимости меняются местами). Выведите отсортированный список через пробел, а на второй строке — количество обменов. Функции `sorted` и `sort` не используйте.\n\nПример: `4` и `3 1 2 4` → `1 2 3 4` и `2`.",
      kk: "Бірінші жолда — сандар саны `n`, екінші жолда — сандардың өздері бос орын арқылы. Тізімді өсу ретімен көпіршік әдісімен сұрыптаңыз (көрші элементтер салыстырылып, қажет болса орындарымен алмасады). Сұрыпталған тізімді бос орын арқылы, ал екінші жолға алмасулар санын шығарыңыз. `sorted` және `sort` функцияларын қолданбаңыз.\n\nМысал: `4` және `3 1 2 4` → `1 2 3 4` және `2`.",
    },
    starter: "n = int(input())\na = list(map(int, input().split()))\ncount = 0\n",
    hint: {
      ru: "Два вложенных цикла: `for i in range(n - 1)` и `for j in range(n - 1 - i)`. Если `a[j] > a[j + 1]`, поменяйте их местами (`a[j], a[j + 1] = a[j + 1], a[j]`) и увеличьте счётчик обменов.",
      kk: "Екі кірістірілген цикл: `for i in range(n - 1)` және `for j in range(n - 1 - i)`. `a[j] > a[j + 1]` болса, оларды алмастырыңыз (`a[j], a[j + 1] = a[j + 1], a[j]`) және алмасулар санауышын арттырыңыз.",
    },
    solution: "n = int(input())\na = list(map(int, input().split()))\ncount = 0\nfor i in range(n - 1):\n    for j in range(n - 1 - i):\n        if a[j] > a[j + 1]:\n            a[j], a[j + 1] = a[j + 1], a[j]\n            count += 1\nprint(*a)\nprint(count)\n",
    check: {
      kind: "python",
      tests: [
        { stdin: "4\n3 1 2 4\n", stdout: "1 2 3 4\n2" },
        { stdin: "1\n5\n", stdout: "5\n0" },
        { stdin: "5\n5 4 3 2 1\n", stdout: "1 2 3 4 5\n10" },
        { stdin: "5\n1 2 3 4 5\n", stdout: "1 2 3 4 5\n0" },
        { stdin: "6\n4 -1 4 0 -7 2\n", stdout: "-7 -1 0 2 4 4\n9" },
        { stdin: "3\n2 2 2\n", stdout: "2 2 2\n0" },
      ],
    },
  },
  {
    id: "py-31-search-binary",
    lang: "python",
    level: 3,
    skill: "py.search",
    title: { ru: "Бинарный поиск", kk: "Екілік іздеу" },
    prompt: {
      ru: "В первой строке — количество чисел `n`, во второй — `n` чисел по возрастанию, в третьей — число `x`. Найдите `x` бинарным поиском: `lo = 0`, `hi = n - 1`; пока `lo <= hi`, берите середину `mid = (lo + hi) // 2` и сравнивайте `a[mid]` с `x`: равны — элемент найден, `a[mid] < x` — ищите правее (`lo = mid + 1`), иначе — левее (`hi = mid - 1`). Выведите номер найденного элемента (с нуля) или `-1`, если его нет, а на второй строке — число шагов (сколько раз вычисляли `mid`). Методы `index`, `find` и `count` не используйте.\n\nПример: `5`, `1 3 5 7 9`, `7` → `3` и `2`.",
      kk: "Бірінші жолда — сандар саны `n`, екінші жолда — өсу ретімен `n` сан, үшінші жолда — `x` саны. `x` санын екілік іздеумен табыңыз: `lo = 0`, `hi = n - 1`; `lo <= hi` болғанша `mid = (lo + hi) // 2` ортасын алып, `a[mid]` мәнін `x` санымен салыстырыңыз: тең болса — элемент табылды, `a[mid] < x` болса — оң жақтан іздеңіз (`lo = mid + 1`), әйтпесе — сол жақтан (`hi = mid - 1`). Табылған элементтің нөмірін (нөлден бастап) немесе ол жоқ болса `-1`, ал екінші жолға қадам санын (`mid` неше рет есептелгенін) шығарыңыз. `index`, `find` және `count` әдістерін қолданбаңыз.\n\nМысал: `5`, `1 3 5 7 9`, `7` → `3` және `2`.",
    },
    starter: "n = int(input())\na = list(map(int, input().split()))\nx = int(input())\nlo = 0\nhi = n - 1\nsteps = 0\n",
    hint: {
      ru: "Заведите `pos = -1` и считайте шаг сразу после вычисления `mid`. Когда элемент найден, запомните `pos` и остановите цикл через `break` — иначе шаги продолжат считаться.",
      kk: "`pos = -1` деп алып, қадамды `mid` есептелген бойда санаңыз. Элемент табылғанда `pos` мәнін сақтап, циклді `break` арқылы тоқтатыңыз — әйтпесе қадамдар санала береді.",
    },
    solution: "n = int(input())\na = list(map(int, input().split()))\nx = int(input())\nlo = 0\nhi = n - 1\nsteps = 0\npos = -1\nwhile lo <= hi:\n    mid = (lo + hi) // 2\n    steps += 1\n    if a[mid] == x:\n        pos = mid\n        break\n    elif a[mid] < x:\n        lo = mid + 1\n    else:\n        hi = mid - 1\nprint(pos)\nprint(steps)\n",
    check: {
      kind: "python",
      tests: [
        { stdin: "5\n1 3 5 7 9\n7\n", stdout: "3\n2" },
        { stdin: "5\n1 3 5 7 9\n4\n", stdout: "-1\n3" },
        { stdin: "1\n3\n3\n", stdout: "0\n1" },
        { stdin: "6\n2 4 6 8 10 12\n2\n", stdout: "0\n2" },
        { stdin: "6\n2 4 6 8 10 12\n12\n", stdout: "5\n3" },
        { stdin: "8\n1 2 3 4 5 6 7 8\n9\n", stdout: "-1\n4" },
        { stdin: "7\n-9 -4 0 3 8 15 20\n-4\n", stdout: "1\n2" },
      ],
    },
  },
  {
    id: "py-32-graph-two",
    lang: "python",
    level: 3,
    skill: "py.graphs",
    title: { ru: "Кратчайший путь по таблице", kk: "Кесте бойынша ең қысқа жол" },
    prompt: {
      ru: "В первой строке — число городов `n`, затем `n` строк по `n` чисел: в строке `i` стоят длины дорог из города `i` в города 1…n (0 — дороги нет). Выведите длину кратчайшего пути из города 1 в город n, который идёт напрямую или через один промежуточный город. Если такого пути нет, выведите `-1`.\n\nПример: `4` и таблица\n\n```\n0 5 9 20\n5 0 4 0\n9 4 0 7\n20 0 7 0\n```\n\n→ `16` (1 → 3 → 4: 9 + 7).",
      kk: "Бірінші жолда — қалалар саны `n`, одан кейін `n` жол, әр жолда `n` сан: `i` нөмірлі жолда `i` қаласынан 1…n қалаларына дейінгі жол ұзындықтары тұр (0 — тікелей жол жоқ). 1 қаласынан `n` қаласына тікелей немесе бір аралық қала арқылы баратын ең қысқа жолдың ұзындығын шығарыңыз. Мұндай жол болмаса, `-1` шығарыңыз.\n\nМысал: `4` және кесте\n\n```\n0 5 9 20\n5 0 4 0\n9 4 0 7\n20 0 7 0\n```\n\n→ `16` (1 → 3 → 4: 9 + 7).",
    },
    starter: "n = int(input())\na = []\nfor i in range(n):\n    a.append(list(map(int, input().split())))\nbest = -1\n",
    hint: {
      ru: "Начните с `best = -1`. Прямая дорога — `a[0][n-1]`, если она не 0. Для каждого промежуточного города `k` от 1 до `n - 2` путь есть, если `a[0][k] > 0` и `a[k][n-1] > 0`; его длина — сумма этих двух. Оставляйте наименьшую длину.",
      kk: "`best = -1` деп бастаңыз. Тікелей жол — `a[0][n-1]`, ол 0 болмаса. Әр аралық `k` қаласы үшін (`k` = 1, …, `n - 2`) `a[0][k] > 0` және `a[k][n-1] > 0` болса, жол бар; оның ұзындығы — осы екеуінің қосындысы. Ең кішісін сақтаңыз.",
    },
    solution: "n = int(input())\na = []\nfor i in range(n):\n    a.append(list(map(int, input().split())))\nbest = -1\nif a[0][n - 1] > 0:\n    best = a[0][n - 1]\nfor k in range(1, n - 1):\n    if a[0][k] > 0 and a[k][n - 1] > 0:\n        d = a[0][k] + a[k][n - 1]\n        if best == -1 or d < best:\n            best = d\nprint(best)\n",
    check: {
      kind: "python",
      tests: [
        { stdin: "4\n0 5 9 20\n5 0 4 0\n9 4 0 7\n20 0 7 0\n", stdout: "16" },
        { stdin: "2\n0 3\n3 0\n", stdout: "3" },
        { stdin: "2\n0 0\n0 0\n", stdout: "-1" },
        { stdin: "3\n0 2 0\n2 0 3\n0 3 0\n", stdout: "5" },
        { stdin: "3\n0 2 10\n2 0 3\n10 3 0\n", stdout: "5" },
        { stdin: "5\n0 4 6 0 30\n4 0 0 0 20\n6 0 0 0 9\n0 0 0 0 0\n30 20 9 0 0\n", stdout: "15" },
        { stdin: "4\n0 1 0 0\n1 0 0 0\n0 0 0 3\n0 0 3 0\n", stdout: "-1" },
      ],
    },
  },
  {
    id: "py-33-debug-range",
    lang: "python",
    level: 1,
    skill: "py.debug",
    title: { ru: "Найди ошибку: границы цикла", kk: "Қатені тап: цикл шекаралары" },
    prompt: {
      ru: "Программа должна вывести сумму чисел от 1 до `n`, но для `n = 5` печатает `10` вместо `15`. Найдите ошибку и исправьте программу.",
      kk: "Программа 1-ден `n` санына дейінгі сандардың қосындысын шығаруы керек, бірақ `n = 5` үшін `15` орнына `10` шығарады. Қатені тауып, программаны түзетіңіз.",
    },
    starter: "n = int(input())\ntotal = 0\nfor i in range(1, n):\n    total += i\nprint(total)\n",
    hint: {
      ru: "Подумайте, какое число `range(1, n)` выдаёт последним: правая граница в перебор не входит.",
      kk: "`range(1, n)` соңында қандай санды беретінін ойланыңыз: оң жақ шекара аралауға кірмейді.",
    },
    solution: "n = int(input())\ntotal = 0\nfor i in range(1, n + 1):\n    total += i\nprint(total)\n",
    check: {
      kind: "python",
      tests: [
        { stdin: "5\n", stdout: "15" },
        { stdin: "1\n", stdout: "1" },
        { stdin: "10\n", stdout: "55" },
        { stdin: "100\n", stdout: "5050" },
      ],
    },
  },
  {
    id: "py-34-debug-call",
    lang: "python",
    level: 1,
    skill: "py.debug",
    title: { ru: "Найди ошибку: вызов функции", kk: "Қатені тап: функцияны шақыру" },
    prompt: {
      ru: "Программа должна вывести сумму двух целых чисел, но при запуске падает с ошибкой `TypeError`. Найдите ошибку и исправьте программу.",
      kk: "Программа екі бүтін санның қосындысын шығаруы керек, бірақ іске қосқанда `TypeError` қатесімен тоқтап қалады. Қатені тауып, программаны түзетіңіз.",
    },
    starter: "a = int(input)\nb = int(input())\nprint(a + b)\n",
    hint: {
      ru: "Прочитайте сообщение об ошибке и номер строки. Сравните эту строку со второй: чем они отличаются? Функцию нужно не просто назвать, а вызвать.",
      kk: "Қате туралы хабарды және жол нөмірін оқыңыз. Осы жолды екінші жолмен салыстырыңыз: олар немен ерекшеленеді? Функцияны атап қана қоймай, шақыру керек.",
    },
    solution: "a = int(input())\nb = int(input())\nprint(a + b)\n",
    check: {
      kind: "python",
      tests: [
        { stdin: "3\n5\n", stdout: "8" },
        { stdin: "-4\n10\n", stdout: "6" },
        { stdin: "0\n0\n", stdout: "0" },
      ],
    },
  },
  {
    id: "py-35-debug-border",
    lang: "python",
    level: 1,
    skill: "py.debug",
    title: { ru: "Найди ошибку: граница условия", kk: "Қатені тап: шарт шекарасы" },
    prompt: {
      ru: "Человек считается совершеннолетним с 18 лет включительно. Программа должна вывести `adult` для возраста 18 и старше и `minor` для младше, но для `18` отвечает неверно. Найдите ошибку и исправьте программу.",
      kk: "Адам 18 жастан бастап (18 қоса) кәмелетке толған болып саналады. Программа 18 және одан үлкен жас үшін `adult`, кіші жас үшін `minor` шығаруы керек, бірақ `18` үшін қате жауап береді. Қатені тауып, программаны түзетіңіз.",
    },
    starter: "age = int(input())\nif age > 18:\n    print(\"adult\")\nelse:\n    print(\"minor\")\n",
    hint: {
      ru: "Проверьте граничное значение: при `age = 18` условие `age > 18` ложно. Какой знак нужен, чтобы 18 тоже подходило?",
      kk: "Шекаралық мәнді тексеріңіз: `age = 18` болғанда `age > 18` шарты жалған. 18 де сәйкес келуі үшін қандай таңба керек?",
    },
    solution: "age = int(input())\nif age >= 18:\n    print(\"adult\")\nelse:\n    print(\"minor\")\n",
    check: {
      kind: "python",
      tests: [
        { stdin: "18\n", stdout: "adult" },
        { stdin: "17\n", stdout: "minor" },
        { stdin: "19\n", stdout: "adult" },
        { stdin: "5\n", stdout: "minor" },
        { stdin: "40\n", stdout: "adult" },
      ],
    },
  },
  {
    id: "py-36-debug-div",
    lang: "python",
    level: 2,
    skill: "py.debug",
    title: { ru: "Найди ошибку: вид деления", kk: "Қатені тап: бөлу түрі" },
    prompt: {
      ru: "Программа должна вывести среднее арифметическое двух целых чисел (результат обычного деления, например `3.5`), но для `3` и `4` выводит `3`. Найдите ошибку и исправьте программу.",
      kk: "Программа екі бүтін санның орташа арифметикалық мәнін (кәдімгі бөлудің нәтижесін, мысалы `3.5`) шығаруы керек, бірақ `3` және `4` үшін `3` шығарады. Қатені тауып, программаны түзетіңіз.",
    },
    starter: "a = int(input())\nb = int(input())\nprint((a + b) // 2)\n",
    hint: {
      ru: "Знак `//` отбрасывает дробную часть. Какой знак даёт обычное деление?",
      kk: "`//` таңбасы бөлшек бөлікті алып тастайды. Кәдімгі бөлуді қандай таңба береді?",
    },
    solution: "a = int(input())\nb = int(input())\nprint((a + b) / 2)\n",
    check: {
      kind: "python",
      tests: [
        { stdin: "3\n4\n", stdout: "3.5" },
        { stdin: "10\n20\n", stdout: "15.0" },
        { stdin: "-1\n2\n", stdout: "0.5" },
        { stdin: "6\n6\n", stdout: "6.0" },
        { stdin: "1\n2\n", stdout: "1.5" },
      ],
    },
  },
  {
    id: "py-37-debug-digits",
    lang: "python",
    level: 2,
    skill: "py.debug",
    title: { ru: "Найди ошибку: условие цикла", kk: "Қатені тап: цикл шарты" },
    prompt: {
      ru: "Программа должна вывести количество цифр натурального числа, но, например, для `5` и `123` отвечает неверно. Найдите ошибку и исправьте программу.",
      kk: "Программа натурал сандағы цифрлар санын шығаруы керек, бірақ, мысалы, `5` және `123` үшін қате жауап береді. Қатені тауып, программаны түзетіңіз.",
    },
    starter: "n = int(input())\ncount = 0\nwhile n > 10:\n    count += 1\n    n //= 10\nprint(count)\n",
    hint: {
      ru: "Проверьте на маленьких числах: для `n = 5` цикл вообще не выполнится. Сколько раз он должен сработать для однозначного числа и верно ли выбрано условие `while`?",
      kk: "Кіші сандармен тексеріңіз: `n = 5` үшін цикл мүлде орындалмайды. Бір таңбалы сан үшін ол неше рет орындалуы керек және `while` шарты дұрыс таңдалған ба?",
    },
    solution: "n = int(input())\ncount = 0\nwhile n > 0:\n    count += 1\n    n //= 10\nprint(count)\n",
    check: {
      kind: "python",
      tests: [
        { stdin: "5\n", stdout: "1" },
        { stdin: "10\n", stdout: "2" },
        { stdin: "123\n", stdout: "3" },
        { stdin: "99\n", stdout: "2" },
        { stdin: "1000000\n", stdout: "7" },
      ],
    },
  },
  {
    id: "py-38-cash-discount",
    lang: "python",
    level: 2,
    skill: "py.context",
    title: { ru: "Касса: скидка", kk: "Касса: жеңілдік" },
    prompt: {
      ru: "**Касса.** Цены товаров (в тенге, целые числа) вводятся по одной на строке, пока не введён `0`. Если сумма покупки не меньше 10000, покупатель получает скидку 10%. Выведите сумму к оплате (целое число; скидка равна `total // 10`).\n\nПример: `6000`, `5000`, `0` → `9900`.",
      kk: "**Касса.** Тауар бағалары (теңгемен, бүтін сандар) әр жолға бір-бірден беріледі, `0` енгізілгенде оқу тоқтайды. Сатып алу сомасы 10000 немесе одан көп болса, сатып алушыға 10% жеңілдік беріледі. Төленетін соманы шығарыңыз (бүтін сан; жеңілдік `total // 10` мәніне тең).\n\nМысал: `6000`, `5000`, `0` → `9900`.",
    },
    starter: "total = 0\n",
    hint: {
      ru: "Читайте цены в цикле `while True:` и прибавляйте к `total`; при `0` — `break`. После цикла проверьте `total >= 10000` и при необходимости вычтите скидку.",
      kk: "Бағаларды `while True:` циклінде оқып, `total` айнымалысына қосыңыз; `0` болғанда — `break`. Циклден кейін `total >= 10000` шартын тексеріп, қажет болса жеңілдікті алып тастаңыз.",
    },
    solution: "total = 0\nwhile True:\n    p = int(input())\n    if p == 0:\n        break\n    total += p\nif total >= 10000:\n    total -= total // 10\nprint(total)\n",
    check: {
      kind: "python",
      tests: [
        { stdin: "6000\n5000\n0\n", stdout: "9900" },
        { stdin: "0\n", stdout: "0" },
        { stdin: "10000\n0\n", stdout: "9000" },
        { stdin: "9999\n0\n", stdout: "9999" },
        { stdin: "2500\n2500\n2500\n2500\n0\n", stdout: "9000" },
        { stdin: "100\n0\n", stdout: "100" },
      ],
    },
  },
  {
    id: "py-39-cash-receipt",
    lang: "python",
    level: 2,
    skill: "py.context",
    title: { ru: "Касса: чек", kk: "Касса: чек" },
    prompt: {
      ru: "**Касса.** В первой строке — число позиций в чеке `n`, затем `n` строк: цена товара и количество через пробел. Выведите итоговую сумму чека, а на второй строке — стоимость самой дорогой позиции (цена × количество).\n\nПример: `3`, `450 2`, `1200 1`, `300 5` → `3600` и `1500`.",
      kk: "**Касса.** Бірінші жолда — чектегі позициялар саны `n`, одан кейін `n` жол: тауардың бағасы және саны бос орын арқылы. Чектің жалпы сомасын, ал екінші жолға ең қымбат позицияның құнын (баға × сан) шығарыңыз.\n\nМысал: `3`, `450 2`, `1200 1`, `300 5` → `3600` және `1500`.",
    },
    starter: "n = int(input())\ntotal = 0\nbest = 0\n",
    hint: {
      ru: "В цикле `for` читайте строку и разбивайте её: `price, qty = map(int, input().split())`. Стоимость позиции — `price * qty`: прибавляйте её к сумме и сравнивайте с наибольшей.",
      kk: "`for` циклінде жолды оқып, оны бөліңіз: `price, qty = map(int, input().split())`. Позицияның құны — `price * qty`: оны сомаға қосып, ең үлкенімен салыстырыңыз.",
    },
    solution: "n = int(input())\ntotal = 0\nbest = 0\nfor i in range(n):\n    price, qty = map(int, input().split())\n    cost = price * qty\n    total += cost\n    if cost > best:\n        best = cost\nprint(total)\nprint(best)\n",
    check: {
      kind: "python",
      tests: [
        { stdin: "3\n450 2\n1200 1\n300 5\n", stdout: "3600\n1500" },
        { stdin: "1\n5000 1\n", stdout: "5000\n5000" },
        { stdin: "2\n100 10\n999 1\n", stdout: "1999\n1000" },
        { stdin: "3\n700 3\n2000 1\n300 2\n", stdout: "4700\n2100" },
        { stdin: "4\n250 4\n1000 1\n50 20\n10 3\n", stdout: "3030\n1000" },
      ],
    },
  },
  {
    id: "py-40-cash-change",
    lang: "python",
    level: 3,
    skill: "py.context",
    title: { ru: "Касса: сдача", kk: "Касса: қайтарылатын ақша" },
    prompt: {
      ru: "**Касса.** Покупатель дал `m` тенге, покупка стоит `p` тенге (m ≥ p; каждое число на своей строке). Выдайте сдачу наименьшим числом купюр и монет номиналами 5000, 2000, 1000, 500, 200, 100, 50, 20, 10, 5, 2, 1. Выведите по одной строке на каждый использованный номинал — от большего к меньшему: номинал и количество через пробел. Если сдачи нет, выведите `0`.\n\nПример: `10000` и `2160` → сдача 7840 →\n\n```\n5000 1\n2000 1\n500 1\n200 1\n100 1\n20 2\n```",
      kk: "**Касса.** Сатып алушы `m` теңге берді, сатып алынған тауар `p` теңге тұрады (m ≥ p; әр сан жеке жолда). Қайтарылатын ақшаны номиналы 5000, 2000, 1000, 500, 200, 100, 50, 20, 10, 5, 2, 1 болатын купюралар мен тиындардың ең аз санымен беріңіз. Пайдаланылған әр номинал үшін бір жол шығарыңыз — үлкенінен кішісіне қарай: номинал және саны бос орын арқылы. Қайтарылатын ақша болмаса, `0` шығарыңыз.\n\nМысал: `10000` және `2160` → қайтарылатын ақша 7840 →\n\n```\n5000 1\n2000 1\n500 1\n200 1\n100 1\n20 2\n```",
    },
    starter: "m = int(input())\np = int(input())\nd = m - p\nnotes = [5000, 2000, 1000, 500, 200, 100, 50, 20, 10, 5, 2, 1]\n",
    hint: {
      ru: "Идите по номиналам от большего к меньшему: каждый раз берите столько купюр текущего номинала, сколько помещается в оставшуюся сумму (`//`), а остаток (`%`) передавайте дальше. Номиналы с нулевым количеством не печатайте.",
      kk: "Номиналдарды үлкенінен кішісіне қарай аралаңыз: әр қадамда қалған сомаға сыятын ағымдағы номиналдың ең көп санын алыңыз (`//`), ал қалдықпен (`%`) келесі номиналға өтіңіз. Саны нөлге тең номиналдарды шығармаңыз.",
    },
    solution: "m = int(input())\np = int(input())\nd = m - p\nnotes = [5000, 2000, 1000, 500, 200, 100, 50, 20, 10, 5, 2, 1]\nif d == 0:\n    print(0)\nfor x in notes:\n    k = d // x\n    d = d % x\n    if k > 0:\n        print(x, k)\n",
    check: {
      kind: "python",
      tests: [
        { stdin: "10000\n2160\n", stdout: "5000 1\n2000 1\n500 1\n200 1\n100 1\n20 2" },
        { stdin: "1000\n1000\n", stdout: "0" },
        { stdin: "20000\n1\n", stdout: "5000 3\n2000 2\n500 1\n200 2\n50 1\n20 2\n5 1\n2 2" },
        { stdin: "500\n499\n", stdout: "1 1" },
        { stdin: "5000\n1000\n", stdout: "2000 2" },
        { stdin: "10000\n5000\n", stdout: "5000 1" },
        { stdin: "1000\n12\n", stdout: "500 1\n200 2\n50 1\n20 1\n10 1\n5 1\n2 1\n1 1" },
      ],
    },
  },
];

/** Ограничения из условия задач (проверяются до запуска). Ключ — id задачи. */
export const PY_FORBID: Record<string, PyForbid[]> = {
  "py-4-max3": [
    {
      re: "\\bmax\\s*\\(",
      why: { ru: "В этой задаче функцию max использовать нельзя — сравните числа через if.", kk: "Бұл есепте max функциясын қолдануға болмайды — сандарды if арқылы салыстырыңыз." },
    },
  ],
  "py-10-binary": [
    {
      re: "\\b(bin|format)\\s*\\(",
      why: { ru: "Функции bin и format использовать нельзя — переводите вручную: делите на 2 и собирайте остатки.", kk: "bin және format функцияларын қолдануға болмайды — қолмен аударыңыз: 2-ге бөліп, қалдықтарды жинаңыз." },
    },
    {
      re: "\\bf[\"'][^\"'\\n]*:[#0-9]*b\\}",
      inStrings: true,
      why: { ru: "Форматирование f\"{n:b}\" использовать нельзя — переводите вручную: делите на 2 и собирайте остатки.", kk: "f\"{n:b}\" пішімдеуін қолдануға болмайды — қолмен аударыңыз: 2-ге бөліп, қалдықтарды жинаңыз." },
    },
  ],
  "py-14-ops-digit": [
    {
      re: "\\bstr\\s*\\(|\\[",
      why: { ru: "В этой задаче строки и индексы использовать нельзя — работайте с цифрами через `//`, `%` и `**`.", kk: "Бұл есепте жолдар мен индекстерді қолдануға болмайды — цифрлармен `//`, `%` және `**` арқылы жұмыс істеңіз." },
    },
  ],
  "py-21-pat-maxpos": [
    {
      re: "\\bmax\\s*\\(|\\.index\\s*\\(",
      why: { ru: "В этой задаче `max` и `index` использовать нельзя — найдите наибольшее циклом.", kk: "Бұл есепте `max` және `index` қолдануға болмайды — ең үлкенін циклмен табыңыз." },
    },
  ],
  "py-22-pat-reverse": [
    {
      re: "\\bstr\\s*\\(|\\breversed\\s*\\(|\\[",
      why: { ru: "В этой задаче строки, индексы и срезы использовать нельзя — работайте с цифрами через `//` и `%`.", kk: "Бұл есепте жолдарды, индекстерді және тілімдерді қолдануға болмайды — цифрлармен `//` және `%` арқылы жұмыс істеңіз." },
    },
  ],
  "py-23-pat-gcd": [
    {
      re: "\\bmath\\b",
      why: { ru: "Модуль math (и его gcd) использовать нельзя — примените алгоритм Евклида.", kk: "math модулін (және оның gcd функциясын) қолдануға болмайды — Евклид алгоритмін пайдаланыңыз." },
    },
  ],
  "py-29-rec-fib": [
    {
      re: "\\b(for|while)\\b",
      why: { ru: "В этой задаче циклы использовать нельзя — функция должна вызывать саму себя.", kk: "Бұл есепте циклдерді қолдануға болмайды — функция өзін-өзі шақыруы керек." },
    },
  ],
  "py-30-sort-bubble": [
    {
      re: "\\bsorted\\s*\\(|\\.sort\\s*\\(",
      why: { ru: "Функции sorted и sort использовать нельзя — отсортируйте методом пузырька.", kk: "sorted және sort функцияларын қолдануға болмайды — көпіршік әдісімен сұрыптаңыз." },
    },
  ],
  "py-31-search-binary": [
    {
      re: "\\.(index|find|count)\\s*\\(",
      why: { ru: "Методы index, find и count использовать нельзя — ищите бинарным поиском.", kk: "index, find және count әдістерін қолдануға болмайды — екілік іздеумен іздеңіз." },
    },
  ],
};
