import {
  ArrowRight,
  Battery,
  Binary,
  Biohazard,
  Bot,
  Box,
  Brain,
  Bug,
  Calculator,
  Camera,
  ChartColumn,
  Check,
  Clock,
  Cloud,
  Code,
  Cpu,
  Database,
  Download,
  File,
  Folder,
  Globe,
  HardDrive,
  Image,
  Key,
  Keyboard,
  Laptop,
  Lightbulb,
  Link,
  Lock,
  LockOpen,
  Mail,
  MemoryStick,
  Mic,
  Monitor,
  Mouse,
  Music,
  Network,
  Package,
  Printer,
  Repeat,
  Rocket,
  Router,
  ScanLine,
  Search,
  Server,
  Settings,
  Shield,
  Smartphone,
  Split,
  Table,
  Terminal,
  Type,
  Upload,
  Usb,
  User,
  Users,
  Video,
  Volume2,
  Wifi,
  X,
  Zap,
  type LucideIcon,
} from "lucide-react";
import type { IconName } from "@/lib/types";

/** Имя иконки из данных (`IconName`) → рисованная иконка lucide. Эмодзи в интерфейсе не используем. */
export const ICONS: Record<IconName, LucideIcon> = {
  cpu: Cpu,
  memory: MemoryStick,
  "hard-drive": HardDrive,
  usb: Usb,
  keyboard: Keyboard,
  mouse: Mouse,
  monitor: Monitor,
  printer: Printer,
  speaker: Volume2,
  mic: Mic,
  camera: Camera,
  scanner: ScanLine,
  laptop: Laptop,
  phone: Smartphone,
  server: Server,
  router: Router,
  wifi: Wifi,
  network: Network,
  globe: Globe,
  cloud: Cloud,
  database: Database,
  table: Table,
  file: File,
  folder: Folder,
  code: Code,
  terminal: Terminal,
  bug: Bug,
  lock: Lock,
  unlock: LockOpen,
  key: Key,
  shield: Shield,
  virus: Biohazard,
  mail: Mail,
  user: User,
  users: Users,
  brain: Brain,
  bot: Bot,
  cube: Box,
  rocket: Rocket,
  lightbulb: Lightbulb,
  chart: ChartColumn,
  image: Image,
  music: Music,
  video: Video,
  text: Type,
  binary: Binary,
  calculator: Calculator,
  clock: Clock,
  zap: Zap,
  check: Check,
  x: X,
  "arrow-right": ArrowRight,
  repeat: Repeat,
  split: Split,
  search: Search,
  settings: Settings,
  link: Link,
  download: Download,
  upload: Upload,
  battery: Battery,
  box: Package,
};

/** Компонент иконки по имени. */
export const iconFor = (name: IconName): LucideIcon => ICONS[name];
